### ISSUE TITLE
stream.Write do not send any packet 

### ISSUE THREAD

**Issue by kyocheng** [lucas-clemente/quic-go#3116] opened 2021-03-22 09:06 UTC
I am a client, and the server, after pressure testing, found that the problem, the client's new stream, in the execution stream.Write When, stream.Write The return value is correct, but tcpdump does not find the sending packet

Core code:

	ctx, _ := context.WithTimeout(context.Background(), 5*time.Second)
	stream, err := session.OpenStreamSync(ctx)
	if err != nil {
		logger.Error("OpenStreamSync error", err)
		qc.client.NotifyFailed(pck, err)
		session.CloseWithError(10,"OpenStreamSync")
		qc.Delete(pck,session)
		return
	}
	logger.Debug("OpenStreamSync Ok")
	defer stream.Close()
	pck.OptType = consts.OperationCreateConnect
	xx, err := stream.Write(protocols.EncryptSendPacket(*pck))
	if err != nil {
		logger.Error("streamWrite error", err)
		qc.client.NotifyFailed(pck, err)
		session.CloseWithError(10,"OpenStreamSync")
		qc.Delete(pck,session)
		return
	}
	

incorrect log  :
DEBUG: 2021/03/21 15:09:11 quic_client.go:110: OpenStream  stream: ch2.dev01.g-proxy.com:11225
2021/03/21 15:09:11 client Sending ACK because the ACK timer expired.
2021/03/21 15:09:11 client -> Sending packet 594 (37 bytes) for connection 0x8dc71f150a7ab11006, 1-RTT
2021/03/21 15:09:11 client      Short Header{DestConnectionID: 0x2503895e, PacketNumber: 594, PacketNumberLen: 2, KeyPhase: 0}
2021/03/21 15:09:11 client      -> &wire.AckFrame{LargestAcked: 675, LowestAcked: 271, AckRanges: {{Largest: 675, Smallest: 639}, {Largest: 637, Smallest: 283}, {Largest: 281, Smallest: 278}, {Largest: 276, Smallest: 271}}, DelayTime: 25.423181ms}
DEBUG: 2021/03/21 15:09:11 quic_client.go:149: OpenStreamSync Ok
2021/03/21 15:09:12 muxer Tracking 1 connection IDs and 1 reset tokens.
2021/03/21 15:09:12 muxer Tracking 1 connection IDs and 1 reset tokens.
2021/03/21 15:09:12 client Sending a keep-alive PING to keep the connection alive.
2021/03/21 15:09:12 client -> Sending packet 12649 (25 bytes) for connection 0x02c545eb6f6694fa6de18c078dd0, 1-RTT
2021/03/21 15:09:12 client      Short Header{DestConnectionID: 0x4cf22ffc, PacketNumber: 12649, PacketNumberLen: 2, KeyPhase: 0}
2021/03/21 15:09:12 client      -> &wire.PingFrame{}
2021/03/21 15:09:12 client <- Reading packet 8022 (21 bytes) for connection (empty), 1-RTT
2021/03/21 15:09:12 client      Short Header{DestConnectionID: (empty), PacketNumber: 8022, PacketNumberLen: 2, KeyPhase: 0}
2021/03/21 15:09:12 client      <- &wire.PingFrame{}
2021/03/21 15:09:12 client      Setting ACK timer to max ack delay: 25ms
2021/03/21 15:09:12 client -> Sending packet 12650 (30 bytes) for connection 0x02c545eb6f6694fa6de18c078dd0, 1-RTT
2021/03/21 15:09:12 client      Short Header{DestConnectionID: 0x4cf22ffc, PacketNumber: 12650, PacketNumberLen: 2, KeyPhase: 0}
2021/03/21 15:09:12 client      -> &wire.AckFrame{LargestAcked: 8022, LowestAcked: 7515, DelayTime: 80.391μs}
2021/03/21 15:09:12 client <- Reading packet 8023 (30 bytes) for connection (empty), 1-RTT
2021/03/21 15:09:12 client      Short Header{DestConnectionID: (empty), PacketNumber: 8023, PacketNumberLen: 2, KeyPhase: 0}
2021/03/21 15:09:12 client      <- &wire.AckFrame{LargestAcked: 12650, LowestAcked: 12201, AckRanges: {{Largest: 12650, Smallest: 12273}, {Largest: 12271, Smallest: 12201}}, DelayTime: 17.168ms}
2021/03/21 15:09:12 client      newly acked packets (1): [12649]
2021/03/21 15:09:12 client Canceling loss detection timer. No packets in flight.
DEBUG: 2021/03/21 15:09:13 quic_client.go:189: for check: <nil>
2021/03/21 15:09:14 muxer Tracking 1 connection IDs and 1 reset tokens.
2021/03/21 15:09:14 muxer Tracking 1 connection IDs and 1 reset tokens.

correct log  :

DEBUG: 2021/03/22 12:54:03 quic_client.go:149: OpenStreamSync Ok
2021/03/22 12:54:03 client -> Sending packet 138 (164 bytes) for connection 0x6c8c5df69a3b545bb90b7db1, 1-RTT
2021/03/22 12:54:03 client      Short Header{DestConnectionID: 0x7602a601, PacketNumber: 138, PacketNumberLen: 2, KeyPhase: 0}
2021/03/22 12:54:03 client      -> &wire.StreamFrame{StreamID: 136, Fin: false, Offset: 0, Data length: 138, Offset + Data length: 138}
2021/03/22 12:54:03 client <- Reading packet 86 (45 bytes) for connection (empty), 1-RTT
2021/03/22 12:54:03 client      Short Header{DestConnectionID: (empty), PacketNumber: 86, PacketNumberLen: 2, KeyPhase: 0}
2021/03/22 12:54:03 client      <- &wire.AckFrame{LargestAcked: 138, LowestAcked: 136, DelayTime: 336μs}
2021/03/22 12:54:03 client      newly acked packets (1): [138]
2021/03/22 12:54:03 client      updated RTT: 10.112ms (σ: 1.343ms)
2021/03/22 12:54:03 client Canceling loss detection timer. No packets in flight.
2021/03/22 12:54:03 client      <- &wire.StreamFrame{StreamID: 136, Fin: false, Offset: 0, Data length: 17, Offset + Data length: 17}
2021/03/22 12:54:03 client      Setting ACK timer to max ack delay: 25ms
DEBUG: 2021/03/22 12:54:03 quic_client.go:170: Read Ok
DEBUG: 2021/03/22 12:54:03 quic_client.go:179: dial to gateway success, then io copy 1m0s 60
2021/03/22 12:54:03 client Sending ACK because the ACK timer expired.
2021/03/22 12:54:03 client -> Sending packet 139 (30 bytes) for connection 0x6c8c5df69a3b545bb90b7db1, 1-RTT
2021/03/22 12:54:03 client      Short Header{DestConnectionID: 0x7602a601, PacketNumber: 139, PacketNumberLen: 2, KeyPhase: 0}
2021/03/22 12:54:03 client      -> &wire.AckFrame{LargestAcked: 86, LowestAcked: 51, DelayTime: 25.450919ms}
2021/03/22 12:54:04 muxer Tracking 1 connection IDs and 1 reset tokens.
2021/03/22 12:54:05 muxer Tracking 1 connection IDs and 1 reset tokens.
DEBUG: 2021/03/22 12:54:05 quic_client.go:191: for check: <nil>
2021/03/22 12:54:06 muxer Tracking 1 connection IDs and 1 reset tokens.

The difference is "client -> Sending packet 138 (164 bytes) "

**Comment by kyocheng** [comment] 2021-03-22 11:49
session  has keepalive

**Comment by kyocheng** [comment] 2021-03-22 12:57
sendWindowSize is zero

**Comment by marten-seemann** [comment] 2021-03-23 09:28
Not sure about your test setup. All of our integration tests pass, so this might be a problem in your setup.
If you want us to investigate this, please create a minimal working example with no external dependencies that reproduces the problem.

**Comment by apmattil** [comment] 2021-03-24 06:49
I can also get to the same situation with proxy implementation.
stream send window will get full under pressure (fast.com), other end will send stream-freeze info to peer.
finally all streams are freezed and no traffic pass.
so server/client side will end up closing session due 'no network traffic'.

**Comment by marten-seemann** [comment] 2021-03-26 03:45
Again, please create a minimal working example, otherwise we won't be able to debug this.

**Comment by apmattil** [comment] 2021-03-26 07:00
patch for echo example:
```
diff --git a/example/echo/echo.go b/example/echo/echo.go
index 7c1ae280..dccb11b0 100644
--- a/example/echo/echo.go
+++ b/example/echo/echo.go
@@ -11,6 +11,7 @@ import (
"io"
"log"
"math/big"
+       "time"

quic "github.com/lucas-clemente/quic-go"
)
@@ -45,8 +46,24 @@ func echoServer() error {
panic(err)
}
// Echo through the loggingWriter
-       _, err = io.Copy(loggingWriter{stream}, stream)
-       return err
+       //_, err = io.Copy(loggingWriter{stream}, stream)
+       buf := make([]byte, len(message))
+       for {
+               n, err := stream.Read(buf)
+               if err != nil {
+                       fmt.Printf("server read err %s\n", err.Error())
+                       return err
+               }
+
+               var werr error
+               _, werr = stream.Write(buf[:n])
+               if err != nil {
+                       fmt.Printf("server write err %s\n", werr.Error())
+                       return err
+               }
+
+       }
+       //return err
}

func clientMain() error {
@@ -64,18 +81,25 @@ func clientMain() error {
return err
}

-       fmt.Printf("Client: Sending '%s'\n", message)
-       _, err = stream.Write([]byte(message))
-       if err != nil {
-               return err
-       }
-
-       buf := make([]byte, len(message))
-       _, err = io.ReadFull(stream, buf)
-       if err != nil {
-               return err
+       go func() {
+               time.Sleep(10 * time.Millisecond)
+               buf := make([]byte, len(message))
+               _, err := stream.Read(buf)
+               if err != nil {
+                       fmt.Printf("read err %s\n", err.Error())
+                       return
+               }
+               fmt.Printf("Client: Got '%s'\n", buf)
+
+       }()
+
+       for i := 0; ; i++ {
+               fmt.Printf("Client%d: Sending '%s'\n", i, message)
+               _, err = stream.Write([]byte(message))
+               if err != nil {
+                       return err
+               }
}
-       fmt.Printf("Client: Got '%s'\n", buf)

return nil
}
```

**Comment by marten-seemann** [comment] 2021-03-28 08:06
This is expected. You're doing the rate-limiting on the read-side on the client, so at some point neither the client nor the server will be able to send more data.

**Closed by marten-seemann** 2021-03-28 08:06 UTC

**Comment by apmattil** [comment] 2021-03-28 15:14
above will affect ALL streams, one stream can hog all the readwindow.
Small variation is if client opens a new stream, error will be 'too many streams'.

I know this is due the fact that there is no congestion window control accross streams.

but error returned to user of the quic-go package are very missleading.
perhaps we could at least return different error in these cases (and if there is any other cases ? like new handshake fails due rx-win full).

**Comment by marten-seemann** [comment] 2021-03-28 15:17
> above will affect ALL streams, one stream can hog all the readwindow.

That's not correct. The connection flow control window is larger than the stream flow control window.

>  Small variation is if client opens a new stream, error will be 'too many streams'.

You can use `OpenStreamSync` to block the call until a stream is available.

>  like new handshake fails due rx-win full).

There's not even a receive window during the handshake...

Really, I don't see any problem here. Everything works as intended.

**Comment by apmattil** [comment] 2021-03-28 19:33
here a patch with OpenStreamSync(), does not help since 2'nd stream will hog all rx window:
```
diff --git a/example/echo/echo.go b/example/echo/echo.go
index 7c1ae280..6e93006f 100644
--- a/example/echo/echo.go
+++ b/example/echo/echo.go
@@ -11,7 +11,12 @@ import (
        "io"
        "log"
        "math/big"
-
+       "time"
+       "strings"
+       "net"
+       "os"
+       "errors"
+       
        quic "github.com/lucas-clemente/quic-go"
 )
 
@@ -45,8 +50,23 @@ func echoServer() error {
                panic(err)
        }
        // Echo through the loggingWriter
-       _, err = io.Copy(loggingWriter{stream}, stream)
-       return err
+       //_, err = io.Copy(loggingWriter{stream}, stream)
+       buf := make([]byte, len(message))
+       for {
+               n, err := stream.Read(buf)
+               if err != nil {
+                       fmt.Printf("server read err %s\n", err.Error())
+                       return err
+               }
+
+               _, werr := stream.Write(buf[:n])
+               if err != nil {
+                       fmt.Printf("server write err %s\n", werr.Error())
+                       return err
+               }
+
+       }
+       //return err
 }
 
 func clientMain() error {
@@ -58,26 +78,76 @@ func clientMain() error {
        if err != nil {
                return err
        }
-
-       stream, err := session.OpenStreamSync(context.Background())
-       if err != nil {
-               return err
+       // start 'ctrl stream'
+       go func() {
+               if err := runStream(session, 1); err != nil {
+                       if strings.Contains(err.Error(), "No recent network activity") {
+                               fmt.Println("session failed on stream 1")
+                               os.Exit(1)
+                       }
+               }               
+       }()
+       // run rest of streams
+       for i := 2 ; ;i++{
+               if err := runStream(session, i); err != nil {
+                       if strings.Contains(err.Error(), "No recent network activity") {
+                               return fmt.Errorf("session failed on stream %d\n", i) 
+                       }
+               }
        }
 
-       fmt.Printf("Client: Sending '%s'\n", message)
-       _, err = stream.Write([]byte(message))
+       //return nil
+}
+
+func runStream(session quic.Session, id int) error {
+       stream, err := session.OpenStreamSync(context.Background())
+       fmt.Println("new stream", id)
+       //stream, err := session.OpenStream()   
        if err != nil {
                return err
        }
-
+       
        buf := make([]byte, len(message))
-       _, err = io.ReadFull(stream, buf)
-       if err != nil {
+       
+       go func() {
+               for i := 0; ; i++ {
+                       time.Sleep(1 * time.Millisecond)
+                       _, err := stream.Read(buf)
+                       if err != nil {
+                               fmt.Printf("read err on stream %d : %s\n", err.Error())
+                              os.Exit(1)
+                       }
+                       fmt.Printf("Client %d: Got '%s'\n", id, buf)
+               }
+
+       }()
+
+       derr := stream.SetWriteDeadline(time.Now().Add(5*time.Second))
+       if derr != nil {
                return err
        }
-       fmt.Printf("Client: Got '%s'\n", buf)
-
-       return nil
+       for i := 0; ; i++ {
+               fmt.Printf("Client %d: Sending %d'%s'\n", id, i, message)
+               n, err := stream.Write([]byte(message))
+               if err != nil {
+                       var e net.Error
+                       if errors.As(err, &e) {
+                               if e.Timeout() {
+                                       derr := stream.SetWriteDeadline(time.Now().Add(5*time.Second))
+                                       if derr != nil {
+                                               return err
+                                       }
+                                       fmt.Printf("Client%d: write deadline\n", id)
+                                       continue
+                               }
+                       }
+                       return err
+               }
+               if n < len(message) {
+                       return fmt.Errorf("short write %d", n)
+               }
+       }
+       
 }
```
result:
```
Client 2: Got 'foobar'
Client 2: Got 'foobar'
Client 2: Got 'foobar'
Client 2: Got 'foobar'
Client2: write deadline
Client 2: Sending 241279'foobar'
Client 2: Got 'foobar'
server read err NO_ERROR: No recent network activity
2021/03/28 22:15:56 NO_ERROR: No recent network activity
```

2. point
what I ment app handshake (as quic-go payload) will not go through while session rx-win is full.

3.point
why do we have this ticket ?
- because write does not return any error
- developer get's finally 'no network activity'
- developer runs case again and uses tcpdump.. after a while no data is passing.
- first this developer thinks.. is the some deadlock (mutex etc) at quic-go ?
- developer makes a ticket.

how can developer understand from error string 'no resent network activity' as he/she is not reading from session (at some stream) fast enough ?
