### ISSUE TITLE
implement a connection keep-alive

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#400] opened 2017-01-18 07:57 UTC
We should implement an option to keep a connection alive. The API would look similar (identical?) to the `IdleConnTimeout` in a `http.Transport` (see [here](https://golang.org/pkg/net/http/#Transport)).

This requires us to send PING frames, as well as to correctly set the `idleTimeout` in the `Session` based on the defined value.

**Comment by lucas-clemente** [comment] 2017-06-19 10:04
Closing this as a duplicate of #525.

**Closed by lucas-clemente** 2017-06-19 10:04 UTC
Labels: client, feature, want-help
