### ISSUE TITLE
h2quic.RoundTripper reusing dead Session / Connection

### ISSUE THREAD

**Issue by heri16** [lucas-clemente/quic-go#931] opened 2017-11-03 01:48 UTC
`h2quic.RoundTripper` keeps a cached session to every host in a map.

However, if i understand correctly from the source code, if there is any connectivity problem to a host, `qerr.NetworkIdleTimeout` is returned as an error from the runLoop, causing the client connection to be closed. Even when the client connection has been closed, `h2quic.RoundTripper` still keeps the dead client with the stale connection it has in its map, and tries to reuse the dead client/session on the next RoundTrip() to the same host. This causes third-party libraries that uses `h2quic.RoundTripper` like Caddy to not be able to recover on failed connectivity.

I thought a better idea would be to automatically detect and flush stale sessions/clients from `h2quic.RoundTripper`. This could be done via `client.session.Context` or some sort of client.isConnClosed()?

Is this bug valid? If so I would like to attempt a fix on this and submit a PR.

**Comment by marten-seemann** [comment] 2017-12-04 02:34
Duplicate of #765.

**Closed by marten-seemann** 2017-12-04 02:34 UTC
Labels: duplicate
