### ISSUE TITLE
0RTT demos?

### ISSUE THREAD

**Issue by utszcrystal** [lucas-clemente/quic-go#3114] opened 2021-03-22 07:59 UTC
http3 client use DialAddrEarly by default, but I use examples in go-quic directory, it do not show 0RTT function and I capture the packets, it alse do not 0-RTT

**Comment by marten-seemann** [comment] 2021-03-22 08:02
Duplicate of #3113.

**Closed** 2021-03-22 08:01 UTC

**Comment by utszcrystal** [comment] 2021-03-22 08:05
> Duplicate of #3113.

please help me! I use quiche as the server, and I use go-quic as client, but go-quic do not provide 0-RTT demos, can you help me and provide how to test 0-RTT using go-quic?

**Comment by marten-seemann** [comment] 2021-03-22 08:11
https://github.com/lucas-clemente/quic-go/blob/master/integrationtests/self/zero_rtt_test.go should contain plenty of examples. Please pay attention to set a `ClientSessionCache` on the `tls.Config`.

**Comment by utszcrystal** [comment] 2021-03-22 11:22
> https://github.com/lucas-clemente/quic-go/blob/master/integrationtests/self/zero_rtt_test.go should contain plenty of examples. Please pay attention to set a `ClientSessionCache` on the `tls.Config`.

thanks very much, I do it successfully
