### ISSUE TITLE
What are the plans for connection migration

### ISSUE THREAD

**Issue by zxfrocky** [lucas-clemente/quic-go#3209] opened 2021-06-23 12:51 UTC
User always change their network from WIFI to 4G , this may cause quic connection would be reconnect，maybe connection migration is the best way，so when does the  connection migration to be implemented ？

**Comment by marten-seemann** [comment] 2021-06-23 17:28
How do you run quic-go on a mobile phone?

**Comment by zxfrocky** [comment] 2021-06-24 02:21
> How do you run quic-go on a mobile phone?

my server run quic-go ,  and the mobile client use google chrome's quic lib, it support connection migration, but quic-go do not support .

**Comment by marten-seemann** [comment] 2021-06-25 01:20
Makes sense.
Then this is a duplicate of #234.

**Closed by marten-seemann** 2021-06-25 01:20 UTC

**Comment by ydnar** [comment] 2021-07-08 21:47
> How do you run quic-go on a mobile phone?

Soon, hopefully: https://github.com/golang/mobile/pull/65
