### ISSUE TITLE
flaky STK test

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#696] opened 2017-06-20 20:08 UTC
```
• Failure [0.104 seconds]
Server Crypto Setup STK verification and creation [It] requires STK 
/home/travis/gopath/src/github.com/lucas-clemente/quic-go/handshake/crypto_setup_server_test.go:709
  Expected
      <[]uint8 | len:185, cap:185>: [82, 69, 74, 0, 3, 0, 0, 0, 83, 84, 75, 0, 33, 0, 0, 0, 83, 86, 73, 68, 40, 0, 0, 0, 83, 67, 70, 71, 153, 0, 0, 0, 116, 111, 107, 101, 110, 32, 48, 25, 4, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 1, 2, 3, 4, 2, 4, 89, 72, 229, 103, 113, 117, 105, 99, 45, 103, 111, 83, 67, 70, 71, 6, 0, 0, 0, 65, 69, 65, 68, 4, 0, 0, 0, 83, 67, 73, 68, 20, 0, 0, 0, 80, 85, 66, 83, 37, 0, 0, 0, 75, 69, 88, 83, 41, 0, 0, 0, 79, 66, 73, 84, 49, 0, 0, 0, 69, 88, 80, 89, 57, 0, 0, 0, 65, 69, 83, 71, 127, 234, 11, 153, 106, 84, 187, 223, 133, 107, 128, 239, 117, 41, 114, 161, 32, 0, 0, 105, 110, 105, 116, 105, 97, 108, 32, 112, 117, 98, 108, 105, 99, 67, 50, 53, 53, 191, 139, 242, 74, 98, 101, 155, 61, 255, 255, 255, 255, 255, 255, 255, 255]
  to contain substring
      <string>: token 0��YH�f
  /home/travis/gopath/src/github.com/lucas-clemente/quic-go/handshake/crypto_setup_server_test.go:708
  Full Stack Trace
  	/home/travis/gopath/src/github.com/onsi/gomega/internal/assertion/assertion.go:69 +0x233
  github.com/onsi/gomega/internal/assertion.(*Assertion).To(0x18cc25a0, 0x8574780, 0x18cc25c0, 0x0, 0x0, 0x0, 0x18cc25c0)
  	/home/travis/gopath/src/github.com/onsi/gomega/internal/assertion/assertion.go:35 +0x80
  github.com/lucas-clemente/quic-go/handshake.glob..func3.10.1()
  	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/handshake/crypto_setup_server_test.go:708 +0x457
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0x18b33980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/handshake/handshake_suite_test.go:12 +0x57
  testing.tRunner(0x18a9ac00, 0x8443c40)
  	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/testing/testing.go:610 +0x8c
  created by testing.(*T).Run
  	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/testing/testing.go:646 +0x2a5
```

**Comment by marten-seemann** [comment] 2017-06-27 16:28
@lucas-clemente: You added the bug label. How do you know this is a bug (i.e. the fault of the non-test code)?

**Comment by lucas-clemente** [comment] 2017-06-27 16:31
I didn't know that was how we defined the bug label – I use it as a category with the other options being feature or enhancement.

**Comment by marten-seemann** [comment] 2017-07-11 09:35
I'm beginning to believe we're seeing a bit flip here. I just ran the STK tests > 25000 times, and didn't see this. The Ginkgo output is pretty useless, because the output of `ContainSubstring` only makes sense for UTF-8 characters. We could think about implementing a new Gomega matcher though.

**Comment by lucas-clemente** [comment] 2017-07-26 07:51
Closing after discussion as we couldn't reproduce it.

**Closed by lucas-clemente** 2017-07-26 07:51 UTC
Labels: bug, flaky
