### ISSUE TITLE
Panic after update to go 1.15

### ISSUE THREAD

**Issue by olehbozhok** [lucas-clemente/quic-go#2724] opened 2020-08-18 10:23 UTC
on run gomicro
got panic after build update to go 1.15
```

panic: qtls.ConnectionState not compatible with tls.ConnectionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.1()
	/home/we/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/internal/handshake/unsafe.go:17 +0x12e

```
It will be werry useful if it will fix

**Comment by marten-seemann** [comment] 2020-08-18 10:32
Duplicate of #2614.

**Closed** 2020-08-18 10:32 UTC
