### ISSUE TITLE
Support for Apps

### ISSUE THREAD

**Issue by Jabervan** [lucas-clemente/quic-go#1204] opened 2018-02-24 07:52 UTC
Related #1183 problems

I try to build a dependency library by Gomobile, and it's been a long time. but failed.
I very much want to integrate quic-go in our apps to solve the problems we facing.
Please share me a sample, thanks very much!

**Comment by marten-seemann** [comment] 2018-02-24 10:08
Closing as a duplicate of #1183.

Feel free to open a new issue if you have any **specific** problems.

**Closed by marten-seemann** 2018-02-24 10:08 UTC
