### ISSUE TITLE
http3.ConfigureTransport

### ISSUE THREAD

**Issue by wireguard-dev** [lucas-clemente/quic-go#3500] opened 2022-08-11 08:54 UTC
Hi! It would be cool if there was a way to configure my HTTP/1 transport to use HTTP/3.

```
transport := &http.Transport{Proxy: http.ProxyURL(Proxy)}

if err = http3.ConfigureTransport(transport); err != nil {
	panic("error transport")
}
```

**Comment by marten-seemann** [comment] 2022-08-12 08:10
Duplicate of #2190.

**Closed by marten-seemann** 2022-08-12 08:10 UTC
