### ISSUE TITLE
Connection always break after 80s or so

### ISSUE THREAD

**Issue by yjp211** [lucas-clemente/quic-go#1597] opened 2018-11-12 13:26 UTC
Version: The latest version
Operating system: MAC and Linux

The official Echo Example can reappears.

Loop Echo Client(loop send-read):
![image](https://user-images.githubusercontent.com/3926181/48349884-7a041f80-e6c0-11e8-921a-e973539c7512.png)
Loop Echo Server(loop read-send):
![image](https://user-images.githubusercontent.com/3926181/48349921-92743a00-e6c0-11e8-8d46-58a444235236.png)

After 80s  connection break：
![image](https://user-images.githubusercontent.com/3926181/48350219-7a50ea80-e6c1-11e8-82ca-cbedcfc24f64.png)

None of the following options seems to affect the timing:
HandshakeTimeout/IdleTimeout/KeepAlive

**Comment by sintanial** [comment] 2018-11-12 20:53
Yep, same problem for me too, on master version !! I also tried to set KeepAlive to true, but it's not helped

**Comment by sintanial** [comment] 2018-11-12 21:08
Attached client and server log files
[client.log](https://github.com/lucas-clemente/quic-go/files/2573610/client.log)
[server.log](https://github.com/lucas-clemente/quic-go/files/2573614/server.log)

**Comment by marten-seemann** [comment] 2018-11-13 05:20
Thanks for the bug reports!
I located the problem, and I'll submit a fix soon.

**Comment by marten-seemann** [comment] 2018-11-13 05:32
So, the problem is the following: When doing a retry (or a version negotiation), the client removes itself from the packet handler map: https://github.com/lucas-clemente/quic-go/blob/b422876a73988f78e59e298b2d846e6a51f4c9b3/packet_handler_map.go#L54-L68
This starts a timer to catch late arriving packets after the regular closing of a session. I think we need to have to different code paths here, one for regular closing and one for the Retry / VNP case.

**Comment by sintanial** [comment] 2018-11-15 22:56
I tried it, works fine

**Closed** 2018-11-16 09:49 UTC
Labels: bug
