### ISSUE TITLE
Memory leak in performance testing when replacing TCP with quic in devp2p networks

### ISSUE THREAD

**Issue by ewagmig** [lucas-clemente/quic-go#2336] opened 2020-02-05 08:57 UTC
Hi there,
  We are developing a p2p networks based on devp2p which is implemented
in Ethereum right now. However, we took the quic suite here to replace the TCP. And the functionality is quite well at the beginning, but the performance especially on the memory is not so good as time goes by. 
Here is the `pprof` view of a 3-day running environment:
```
➜  Downloads go tool pprof -base 210.20200105-180001.heap 210.20200108-160001.heap
File: you-linux-1577087846
Build ID: 45c984bc21cb33205dbf2db0eb2221591268f8de
Type: inuse_space
Time: Jan 5, 2020 at 6:00pm (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 2490.30MB, 56.58% of 4401.37MB total
Dropped 508 nodes (cum <= 22.01MB)
Showing top 10 nodes out of 190
      flat  flat%   sum%        cum   cum%
  661.40MB 15.03% 15.03%   700.40MB 15.91%  github.com/lucas-clemente/quic-go.(*session).postSetup
  565.31MB 12.84% 27.87%   565.31MB 12.84%  github.com/lucas-clemente/quic-go.init.0.func1
  292.54MB  6.65% 34.52%   355.06MB  8.07%  github.com/lucas-clemente/quic-go/internal/handshake.newCryptoSetup
  292.05MB  6.64% 41.15%   292.05MB  6.64%  crypto/aes.newCipher
  201.06MB  4.57% 45.72%   201.06MB  4.57%  crypto/aes.(*aesCipherGCM).NewGCM
  135.18MB  3.07% 48.79%   135.18MB  3.07%  github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).Get
  107.14MB  2.43% 51.23%   119.65MB  2.72%  crypto/x509.parseCertificate
   85.03MB  1.93% 53.16%   149.04MB  3.39%  github.com/lucas-clemente/quic-go.newStream
   77.02MB  1.75% 54.91%    77.02MB  1.75%  github.com/lucas-clemente/quic-go.(*frameSorter).push
   73.56MB  1.67% 56.58%    73.56MB  1.67%  github.com/marten-seemann/qtls.Client
(pprof)
```
The heap files are attached as below:
[pprof_heap_file.tar.gz](https://github.com/lucas-clemente/quic-go/files/4158332/pprof_heap_file.tar.gz)

#quic dependency:
The quic-go version is `v0.11.1`

Did there anybody meet the same performance issue with us or we implemented quic suite in a wrong manner?
Thanks in advance~

**Comment by marten-seemann** [comment] 2020-02-05 10:47
Hello @ewagmig, thanks for providing these numbers.
Is there any reason you’re using v0.11.1? That version is really old by now, and we’ve changed quite a bit since then.
Could you update to the current version (v0.14.3)?

**Comment by ewagmig** [comment] 2020-02-05 11:26
OK, we will have a try and update latest info on it.

**Comment by ewagmig** [comment] 2020-02-13 03:26
Hi @marten-seemann, we have upgraded the quic version to latest version(v0.14.3) and take some testing on memory performance. It seems that there is still memory leak existence.
From the picture on the memory monitoring: 
<img width="999" alt="memory leak" src="https://user-images.githubusercontent.com/37991051/74398619-38c66680-4e53-11ea-8a01-ac751c0ddfcc.png">
There could be some gc periodically, but the memory went up eventually. 
I have searched out 1 PR(https://github.com/lucas-clemente/quic-go/pull/1847) on this and want to know if there is something to do with it?

**Comment by marten-seemann** [comment] 2020-02-13 04:21
As I've explained in https://github.com/lucas-clemente/quic-go/pull/1847#issuecomment-478493886, it's not really a memory leak.

Can you get some stats about where that memory is allocated?

**Comment by ewagmig** [comment] 2020-02-13 08:21
OK, I will try to get the `pprof` on this container.

**Comment by ewagmig** [comment] 2020-02-16 09:52
Hi @marten-seemann, it's weird that there is no significant memory leak as before, when I posted at the first time. 
Here is the latest pprof info based on these days heap snapshot:
```
➜  Downloads go tool pprof -base 02141734.heap 02161700.heap
File: you-linux-amd64
Build ID: e588f5f7407132213201526a1199d0d59fbdbf88
Type: inuse_space
Time: Feb 14, 2020 at 5:34pm (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for -14.16MB, 11.10% of 127.48MB total
Dropped 5 nodes (cum <= 0.64MB)
Showing top 10 nodes out of 254
      flat  flat%   sum%        cum   cum%
  -30.48MB 23.91% 23.91%   -30.48MB 23.91%  github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).Get
    9.45MB  7.41% 16.49%     9.45MB  7.41%  github.com/syndtr/goleveldb/leveldb/memdb.(*DB).Put
    2.81MB  2.21% 14.29%     2.81MB  2.21%  github.com/deckarep/golang-set.(*threadUnsafeSet).Add
       2MB  1.57% 12.72%        2MB  1.57%  gitlab.iyouchain.com/youchain/go-youchain/core/types.CopyHeader
       2MB  1.57% 11.15%     4.81MB  3.77%  gitlab.iyouchain.com/youchain/go-youchain/you.(*peer).SendConsenuse
   -1.94MB  1.52% 12.67%    -0.44MB  0.35%  github.com/hashicorp/golang-lru/simplelru.(*LRU).Add
   -1.50MB  1.18% 13.85%     3.81MB  2.99%  gitlab.iyouchain.com/youchain/go-youchain/you.(*peer).broadcast
    1.50MB  1.18% 12.67%     1.50MB  1.18%  container/list.(*List).insertValue
       1MB  0.78% 11.89%        1MB  0.78%  gitlab.iyouchain.com/youchain/go-youchain/core/bloombits.NewGenerator
       1MB  0.78% 11.10%        1MB  0.78%  math/big.(*Int).Bytes
```
Is there anything improved in current quic(v0.14.3) implementations or what we found at first is not the case? Then how can `pprof` heap statistics on the previous quic version(v0.11.0) to be in different situation?

**Comment by marten-seemann** [comment] 2020-02-16 09:57
Looks like quic-go doesn't show up in the pprof at all. There were tons of changes between v0.11.0 and v0.14.3.

https://github.com/lucas-clemente/quic-go/issues/2336#issuecomment-585531770 was recorded with v0.14.3, wasn't it? It looks like there's still a memory leak there, doesn't it?

**Comment by ewagmig** [comment] 2020-02-16 10:29
Yes, quic-go did not show up the top 10 in the `pprof`. However, it showed in a quite low level. Here is the top 100 on the heap files:
```
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*baseServer).createNewSession
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*baseServer).handleInitialImpl
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*baseServer).handlePacket.func1
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*baseServer).handlePacketImpl
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*client).establishSecureConnection.func1
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*framerI).AppendStreamFrames
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*packetPacker).PackPacket
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*packetPacker).composeNextPacket
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*packetPacker).maybePackAppDataPacket
         0     0% 18.26%    -0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*receiveStream).Read
         0     0% 18.26%    -0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*receiveStream).readImpl
         0     0% 18.26%    -0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*sendStream).Write
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*sendStream).popNewOrRetransmittedStreamFrame
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*sendStream).popStreamFrame
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*session).run
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*session).sendPacket
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.(*session).sendPackets
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.glob..func2
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go.newConnIDManager
         0     0% 18.26%        1MB  1.40%  github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).RunHandshake.func1
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).SetReadKey
         0     0% 18.26%     0.50MB   0.7%  github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).WriteRecord
```
I have attached the heap files as below: 
[pprof_heapfile_quic.tar.gz](https://github.com/lucas-clemente/quic-go/files/4209639/pprof_heapfile_quic.tar.gz)


#2336 (comment) was recorded with v0.14.3 and it looks like there is still memory leak from the graph. However, we do not know where to find the leak because this time quic-go implementation did not show so apparently.

**Comment by ewagmig** [comment] 2020-02-16 12:03
Hi @marten-seemann updated the graph with `memory_rss` metrics, this corresponds to the heap files grab by `pprof`. 
<img width="978" alt="截屏2020-02-16下午7 21 54" src="https://user-images.githubusercontent.com/37991051/74604287-59aee600-50f7-11ea-8ade-97fe6783a362.png">

**Comment by marten-seemann** [comment] 2020-02-16 13:56
0.5 MB is not really something I'd worry about. This could be caused by a single (or a few) handshakes that were running at the time the pprof was recorded.

Any idea how we can find out what's actually going on here?

**Comment by ewagmig** [comment] 2020-02-17 01:23
Hi @marten-seemann, with current version there is no solid proof of leak as with previous version(v0.11.0). 
We are also puzzled right now and we need more investigation before getting
the root cause of this.

**Comment by marten-seemann** [comment] 2020-02-17 03:48
@ewagmig Thank you. I'll close the issue for now. Please feel free to open a new issue if you encounter any problems.

**Closed by marten-seemann** 2020-02-17 03:48 UTC
