### ISSUE TITLE
http3.Server provides an empty http.Request.TLS property

### ISSUE THREAD

**Issue by ameshkov** [lucas-clemente/quic-go#3596] opened 2022-10-14 15:45 UTC
`requestFromHeaders` only initializes empty `tls.ConnectionState` which is never filled with actual information:
https://github.com/lucas-clemente/quic-go/blob/f78683abb64544398706e04847d4f6ff298aa2e2/http3/request.go#L104

Connection State can be copied from `quic.Connection` once the request is created.

**Comment by marten-seemann** [comment] 2022-10-14 16:02
Duplicate of #2879.

**Closed by marten-seemann** 2022-10-14 16:02 UTC
