### ISSUE TITLE
ciphersuite is not set when it should be

### ISSUE THREAD

**Issue by DesWurstes** [lucas-clemente/quic-go#3625] opened 2022-12-04 17:52 UTC
When I do:
```
mux.HandleFunc("/upload.html", func(w http.ResponseWriter, req *http.Request) {
...
```

req.TLS.CipherSuite is always zero?

**Comment by marten-seemann** [comment] 2022-12-06 06:40
Duplicate of https://github.com/lucas-clemente/quic-go/issues/2879.

**Closed by marten-seemann** 2022-12-06 06:40 UTC
