### ISSUE TITLE
Why did ACK for ACK happen?

### ISSUE THREAD

**Issue by jflyup** [lucas-clemente/quic-go#308] opened 2016-08-30 03:17 UTC
I've  read the code for handling the ACK frames, and do some tests after some modification for my own purpose. When I send only a ACK frame (I enable SendOnlyAck) to peer, the peer will call `receivedPacketHandler.ReceivedPacket()`, then `receivedPacketHandler.stateChanged` will be `true`, and a ACK frame will be sent, and so on. I'm wondering how you avoid this scenario since I didn't find the specific code in `sent_packet_handler.go` `received_packet_handler.go` for it. Can you explain a little? Thanks.

**Comment by lucas-clemente** [comment] 2016-08-30 08:31
Thanks for your report! This is indeed an issue with our current implementation, in fact we already have an issue for it (#85, although its title could be clearer). It's in our current milestone, so should be fixed in the next few weeks.

I'm not 100% sure on the solution (will have to check out the Chrome source), but I think simply not ACKing packets containing solely non-retransmittable frames should be okay, since no retransmissions should happen then. We just have to make sure the congestion doesn't have a problem with that.

Note also that currently we delay packets containing only ACKs for up to 5ms (may increase in the future). That means in practice these cascading ACKs shouldn't be a big issue. Of course this is not a proper fix ;-)

I'm closing this issue as a duplicate of #85. If you have any additional comments, please feel free to write them here anyway (or in #85).

**Closed by lucas-clemente** 2016-08-30 08:31 UTC
