### ISSUE TITLE
Packets In-Order?

### ISSUE THREAD

**Issue by phifty** [lucas-clemente/quic-go#464] opened 2017-03-03 11:28 UTC
Hi,

I've wrote a simple test where a quic server simply echos back the data that a quic client has sent and closes the connection.

In detail, the server
1. Gets a session in Secure state
2. Accepts a stream
3. Reads a block of data
4. Writes back the data
5. Closes the stream
6. Closes the session

The client
1. Opens the session
2. Opens the stream
3. Writes some test data
4. Reads back that data
5. Closes the stream
6. Closes the session

There seem to be a race condition, when the client reads back the data (step 4). Sometimes the `Read` returns a `PeerGoingAway` error before the data was read. Could it be, that the close packet is received before the data packet?

**Comment by marten-seemann** [comment] 2017-03-06 07:28
Hi @phifty,

thanks for testing. What you're seeing can be caused by two things: First, as you already suggested, you could see a reordering of packets. Second, even with perfect in-order delivery, if your application is reading too slowly from the stream, `Stream.Read` will return an error as soon as the CONNECTION_CLOSE was processed.

 I looked at Google's QUIC implementation, and as far as I can see there's no special treatment of `PeerGoingAway`s, as compared to other CONNECTION_CLOSE reasons. That means that as soon as Chrome does the same: as soon as it receives a CONNECTION_CLOSE, it immediately closes the connection (not sure about the error returned from the stream though, I'm not that familiar with their code).

I think what we're seeing here, is a race condition in the protocol itself. In the `h2quic` package it doesn't occur because the server only closes initiates a closing of the connection after the `DefaultIdleTimeout` (30s), i.e. when there's no network activity for 30 seconds. This seems to work reasonably well for H2 over QUIC.

At the moment, there is an ongoing discussion in the QUIC WG about a clean connection teardown, unfortunately spread over a larger number of issues and mailing list threads. I don't think that we're close to a consensus here, so it's a good time to jump into the discussion!

- https://github.com/quicwg/base-drafts/issues/330
- https://github.com/quicwg/base-drafts/issues/353
- https://github.com/quicwg/base-drafts/issues/347
- https://mailarchive.ietf.org/arch/msg/quic/oxQF6Ax07bfsagWjxWVG5IekXFU
- https://mailarchive.ietf.org/arch/msg/quic/awD1plcs68V7VfPTRXNrD43xHJ0

**Comment by marten-seemann** [comment] 2018-01-04 08:02
Connection Closing was updated by the QUIC WG a couple of weeks ago: https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.7.9.

The conclusion for this issue is that you shouldn't close the server if haven't made sure that the client has received all data.
The analogy to TCP doesn't hold here: When you close a TCP connection, all data will be reliably transmitted. The corresponding object to a TCP connection therefore is a QUIC stream: When you close a QUIC stream, all data will be reliably transmitted.

**Closed by marten-seemann** 2018-01-04 08:02 UTC
Labels: bug

**Comment by DeedleFake** [comment] 2021-06-03 03:57
I seem to be having a similar problem, but with `v0.21.0`. Because neither `SendStream.Write()` nor `SendStream.Close()` block and wait for the final `STREAM` frame with `FIN` set to be acknowledged, there doesn't seem to be any way to guarantee that the peer has gotten all of the data before closing the connection, resulting in a seemingly unresolvable data race. I can't even manually acknowledge it because I'd just get the exact same problem the other direction. Am I just missing something?

**Comment by marten-seemann** [comment] 2021-06-03 04:14
@DeedleFake Sounds like you re-discovered the Two Generals Problem: https://en.wikipedia.org/wiki/Two_Generals%27_Problem.

That said, in the future it might be a better idea to open a new issue than trying to resurrect a discussion that had been dead for more than 3 years.

**Comment by DeedleFake** [comment] 2021-06-03 05:36
I know what the Two Generals Problem is and this isn't it. This is a race between writing a small packet and closing the session. I've been going through a decently large chunk of `quic-go`'s codebase and it seems that it's being caused by my calling `Listener.Close()`, which in turn closes all of the accepted `Session`s, sending `CONNECTION_CLOSE` frames to all of the peers and breaking any existing streams with untransmitted data. Since neither `Write()` nor `Close()` block for streams if the data written is small enough to fit into a packet, there's no way to guarantee that all of the data has been sent before the session is closed. It's a data race, and, as far as I can tell, a bug in `quic-go`. Sometimes it works because of convenient timing and sometimes it doesn't, the classic staple of a data race.

Sorry about reviving this issue, but I thought that it might not have been fixed after all so I thought it made sense. If you think that what I detailed above is actually a bug, I'll file a new one.

**Comment by marten-seemann** [comment] 2021-06-03 05:42
> which in turn closes all of the accepted Sessions, sending CONNECTION_CLOSE frames to all of the peers and breaking any existing streams with untransmitted data. Since neither Write() nor Close() block for streams if the data written is small enough to fit into a packet, there's no way to guarantee that all of the data has been sent before the session is closed.

That's true, but even if we guaranteed that the data was sent out, there'd be no guarantee that it would be received (the packet could be lost).
If you want to make sure that data was actually received by the peer, you can't close the connection before you haven't received an explicit signal from the peer.

**Comment by DeedleFake** [comment] 2021-06-03 06:24
Because I have no guarantee that the latest bytes will even attempt to be sent, how can I reliably signal the peer? Isn't the whole point of QUIC to make data transmission reliable enough for dependable usage via timeouts and retransmission, like in TCP? I'm calling `SendStream.Write()` but the bytes that I'm passing to it _never get sent to the other end at all_ unless I just wait for an arbitrary amount of time via `time.Sleep()`. Then they get sent. That seems like incorrect behavior to me.

I seem to have no way at all to know if the library has actually attempted to send the bytes that I gave it or not, which means that I can't ever know when to close the connection. I can safely close a _stream_, which results in the remote end getting the bytes and returning `io.EOF` from its read operation, but closing it still doesn't guarantee that any attempt has been made to send them, or will be made before the session is closed. In fact, the example code _and_ the usage of various `quic-go` components in the `http3` package _never_ seem to close any `Session`s or `Listener`s unless there's an unrecoverable error.

**Comment by marten-seemann** [comment] 2021-06-03 06:40
> I'm calling SendStream.Write() but the bytes that I'm passing to it never get sent to the other end at all unless I just wait for an arbitrary, but long enough, amount of time via time.Sleep().

Same in TCP. Packets get lost sometimes. Retransmissions might get lost as well. Really, this is no different than TCP.

As I said before, if you want to close the session from the sender's side, you'll need a signal from the receiver that it received all the data. That part is not hard to implement. If you're hoping that QUIC will offer you a solution to the Two Generals Problem, you're out of luck though.

**Comment by DeedleFake** [comment] 2021-06-03 07:42
_I literally can't send a signal because the library doesn't even try to send the bytes that I give it._ This is _not_ the Two Generals Problem. The problem here is _entirely_ contained to one machine. It has _nothing_ to do with network conditions or lost packets.

https://github.com/lucas-clemente/quic-go/blob/af3e1008ad94c64d5a60d1d7b2ddc579bca4ca79/send_stream.go#L116-L120

In order to save a frame, the library will hold excess bytes that will fit into a single frame so that, if the stream is closed, it can send those last bytes with the `FIN` bit set instead of having to send an empty `STREAM` frame with the bit set. It _will_ attempt to send them if `SendStream.Close()` is called, but there is a race condition that exists between that call and closing the session that the stream is part of, meaning that that frame _might_ be lost completely before even getting put out onto the network at all. I can't send a signal back because the same problem exists on both ends because both ends are using this library. The only way that I can get the library to reliably attempt to send data is by either passing a large enough amount to `Write()` that it can't hold on to it to save a frame later, or to close the connection, which _does_ reliably send a `CONNECTION_CLOSE` frame which, unfortunately, is not exactly great for carrying custom data that isn't an error code.

The following workaround _does_ work:

Sender's end:
```go
fakeFunctionToIndicateSendingData()

_, err = s.Read(make([]byte, 1))
if err != nil {
  var apperr *quic.ApplicationError
  if errors.As(err, &apperr) {
    if apperr.ErrorCode == quic.ApplicationErrorCode(quic.NoError) {
      return // Cleanup is deferred.
    }
  }
  fakeFunctionToIndicateErrorHandling()
}
```

Receiver's end:
```go
fakeFunctionToIndicateReadingTheDataAndClosingTheStream()

err = session.CloseWithError(quic.ApplicationErrorCode(quic.NoError), quic.NoError.Message())
fakeFunctionToIndicateErrorHandling()
```

Is this the recommended pattern? Because nothing else seems to work because the library _literally won't send the data that I give it_.

And no, Go's TCP implementation does _not_ have this problem. I tested it with `net.TCPConn` and it had no issues at all, even if I called `SetNoDelay(false)`. No matter what timing I used, if I called `Write()` before calling `Close()` it would always transmit the data _before_ closing the connection.

**Comment by DeedleFake** [comment] 2021-06-03 16:18
Alright, it's not 3:00 A.M. anymore. Let me see if I can clarify a bit. Sorry for getting so frustrated.

Here's the actual problem I'm having: If I want to write something and then close just a stream, it works just fine. If I write something to a stream, close the stream, and then also close the _session_, on the other hand, it doesn't necessarily process the bytes that I wrote before the close in the runloop, resulting in them never getting sent. Is my only option to deal with this to close the session from whichever end last received data, and is this expected behavior or should a clean close flush any remaining packets before closing?

As a followup, is the correct, clean way to close a session to call `Session.CloseWithError()` and give it something specific to the application-layer protocol that I'm actually implementing? There doesn't seem to be any consistent way to trigger a call to `session.closeLocal(nil)` without closing the associated `Listener`, but that only works on the server's side and, obviously, I can only do that if I want to actually close the `Listener`.
