### ISSUE TITLE
session CloseWithError() receives error value as string

### ISSUE THREAD

**Issue by apmattil** [lucas-clemente/quic-go#3029] opened 2021-02-03 07:42 UTC
at the receiving side only way to check the sent error code is parse the string.
so in practice error code parameter at sending side (CloseWithError()) is obsolete.

please do not just remove the error code parameter, perhaps make a new error type for session errors ?

**Comment by marten-seemann** [comment] 2021-02-03 07:44
Duplicate of #2441.

**Closed by marten-seemann** 2021-02-03 07:44 UTC
