### ISSUE TITLE
Error returned to AcceptStream is of a type defined in internal package on closing the session

### ISSUE THREAD

**Issue by vrngupta53** [lucas-clemente/quic-go#2958] opened 2020-12-25 21:16 UTC
When the session is closed, the peer gets an error of type qerr.QuicError from AcceptStream function. Am I just supposed to parse the error string if I want to handle this error, like for example if I want to ignore it if the error code is 0x0?

**Comment by marten-seemann** [comment] 2020-12-26 03:19
Duplicate of https://github.com/lucas-clemente/quic-go/issues/2441.

**Closed by marten-seemann** 2020-12-26 03:19 UTC
