### ISSUE TITLE
gquic: Received a packet with an unexpected connection ID

### ISSUE THREAD

**Issue by mholt** [lucas-clemente/quic-go#1743] opened 2019-01-18 20:54 UTC
I'm trying to get QUIC working in Caddy after a USR1 graceful reload; this means that Caddy gets a copy of the file descriptors underlying the sockets and then uses them in the new, reloaded instance to create listeners/PacketConns to set up "new" sockets. For TCP, this enables graceful restarts; for UDP, this should just move packets over to the new process/socket.

You can see the code for this dance here: https://sourcegraph.com/github.com/mholt/caddy@771dcf3d403fe862f5afa040309fa1db7b067554/-/blob/caddy.go#L705

The problem I'm having is that after doing this, QUIC no longer functions. The browser hangs for a few seconds while it renegotiates a regular TCP/TLS connection. It works fine before the reload.

The very first errors are:

```
muxer error handling packet from <ip>:1026: received a packet with an unexpected connection ID 0x538e276ef9b47552
```

And then they repeat every time I try refreshing in the browser.

I have verified that this connection ID are always new, even when starting a very new session in the browser (i.e. going incognito or opening Guest Mode). In other words, the connection IDs before and after the reload are different.

It seems like the QUIC library is refusing to make new servers for these new connection IDs, but whether the socket file is new or reused shouldn't really matter, should it?

The error appears to be emitted from here: https://github.com/lucas-clemente/quic-go/blob/714f38d5d0aff85894fd890718b991e361f03e7d/packet_handler_map.go#L165

So the server is nil, so there is no handler for the given connection ID. But shouldn't QUIC make one the first time it sees a new connection ID? (I'm not totally clear how gQUIC protocol works under the hood.)

Any tips would be helpful, if you can. Thank you!

**Comment by marten-seemann** [comment] 2019-01-23 02:37
I added some more logging to the `packetHandlerMap`, and this is what I'm getting:
```
2019/01/23 09:29:15 [INFO] Successfully loaded TLS assets from /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/example/fullchain.pem and /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/example/privkey.pem
Activating privacy features... done.
https://quic.clemente.io
2019/01/23 09:29:15 https://quic.clemente.io
WARNING: File descriptor limit 7168 is too low for production servers. At least 8192 is recommended. Fix with `ulimit -n 8192`.
2019/01/23 09:29:15 muxer newPacketHandlerMap: &net.UDPConn{conn:net.conn{fd:(*net.netFD)(0xc0001ba400)}}
2019/01/23 09:29:15 muxer packetHandlerMap: SetServer &net.UDPConn{conn:net.conn{fd:(*net.netFD)(0xc0001ba400)}}
2019/01/23 09:29:15 server Listening for udp connections on [::]:443
2019/01/23 09:29:17 [NOTICE] Sending telemetry: we were too early; waiting 1h0m13.553153324s before trying again
2019/01/23 09:29:25 [INFO] SIGUSR1: Reloading
2019/01/23 09:29:25 [INFO] Reloading
2019/01/23 09:29:25 [INFO] Successfully loaded TLS assets from /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/example/fullchain.pem and /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/example/privkey.pem
2019/01/23 09:29:25 [INFO] Reloading complete
2019/01/23 09:29:25 [INFO][FileStorage:/Users/marten/.caddy] Stopped certificate maintenance routine
2019/01/23 09:29:25 muxer packetHandlerMap: CloseServer &net.UDPConn{conn:net.conn{fd:(*net.netFD)(0xc0001ba400)}}
2019/01/23 09:29:25 serving QUIC connections: server closed
2019/01/23 09:29:25 muxer newPacketHandlerMap: &net.UDPConn{conn:net.conn{fd:(*net.netFD)(0xc0001ba500)}}
2019/01/23 09:29:25 muxer packetHandlerMap: SetServer &net.UDPConn{conn:net.conn{fd:(*net.netFD)(0xc0001ba500)}}
2019/01/23 09:29:25 server Listening for udp connections on [::]:443
2019/01/23 09:29:31 muxer error handling packet on &net.UDPConn{conn:net.conn{fd:(*net.netFD)(0xc0001ba400)}} from 127.0.0.1:60974: received a packet with an unexpected connection ID 0x439b56c7d87bc10c
```

So when we first start the server, the `packetHandlerMap` is initialized with the packet conn having the fd `0xc0001ba400`. After the USR1, we're stopping the server on this connection and creating a new `packetHanderMap` using a different packet conn (fd `0xc0001ba500`). However, packets still arrive on the old packet conn, whose server we already stopped, so they get discarded.

I'm not really familiar with the expected behavior of the USR1, but shouldn't file descriptor stays the same, and be passed from the old to the new process?

**Comment by mholt** [comment] 2019-01-23 03:02
Hm, yeah, so USR1 makes a copy of the file descriptor, makes a new listener/socket with it, then closes the old one: https://sourcegraph.com/github.com/mholt/caddy@771dcf3d403fe862f5afa040309fa1db7b067554/-/blob/caddy.go#L767-779

The copied file descriptor is then used to ListenPacket: https://sourcegraph.com/github.com/mholt/caddy@771dcf3d403fe862f5afa040309fa1db7b067554/-/blob/caddyhttp/httpserver/server.go#L300

Interesting that the "received a packet with an unexpected connection ID" error happens on the old file descriptor, 0xc0001ba400. I would have expected "serving QUIC connections: server closed" (a few lines above) to mean that it would no longer receive or handle packets.

It may very well be that we're handling the QUIC library / server wrong when doing graceful reloads. Even if there's not really a way to do a 'graceful' reload for QUIC, I just want to be sure we can shut down the old server and use the new one successfully. Figured I'd open the issue, since I'm not sure if it's in Caddy or in quic-go that it needs to happen.

**Comment by marten-seemann** [comment] 2019-01-23 03:34
If you pass a packet conn to `Listen` (i.e., if you don't use `ListenAddr`), it's the caller's responsibility to close the connection. The reason is the following: Since QUIC uses connection IDs to associate packets with connection, this allows you to run a server and multiple clients on the same packet conn (you'd do that by using the same packet conn to `Dial`).
That's why `Server.Close()` just removes the server from the `packetHandlerMap`, which after that will continue listening on the conn until reading fails.

From the log output I'm getting, it looks like we're never stopping to listen from the old connection. Are you sure that you're closing correctly? I'm not sure I fully understand how the `net.FilePacketConn` works, since the [documentation says](https://golang.org/pkg/net/#FilePacketConn):
> FilePacketConn returns a copy of the packet network connection corresponding to the open file f. It is the caller's responsibility to close f when finished. Closing c does not affect f, and closing f does not affect c.

**Comment by marten-seemann** [comment] 2019-01-25 06:02
I wrote a minimal example to figure out how closing the `os.File` of a `net.PacketConn` works: https://gist.github.com/marten-seemann/8c05883013c50653e4375412fb9edd2d.

This code starts listening on a `net.PacketConn`, and panics as soon as the call the `ReadFrom` returns. When I call `Close` on the `net.PacketConn`, this works as expected, however, if I first retrieve the `os.File`, and then only close that, `ReadFrom` does not return.
If I understand the graceful restart code correctly, this is what's happening during Caddy's graceful restart, meaning that the go-routine reading UDP packets in the `packetHandlerMap` in quic-go never returns.

Does that make sense to you or am I missing something here?

**Comment by mholt** [comment] 2019-01-26 20:54
In that standalone example, it makes sense -- thanks for that. (The simpler example was a good idea.)

However, I don't think it explains the behavior (or, I am still not understanding); why would the quic server say that the connection ID is unexpected, even after calling `quicServer.Close()`  ([here](https://sourcegraph.com/github.com/mholt/caddy@fdec3c68f0ba761cff340c78138c5093598b28a5/-/blob/caddyhttp/httpserver/server.go#L337))? Note that this is separate from the graceful restart code where Caddy copies the file descriptor, [here](https://sourcegraph.com/github.com/mholt/caddy@fdec3c68f0ba761cff340c78138c5093598b28a5/-/blob/caddy.go#L776). 

The QUIC server is operating on a PacketConn, not an os.File, due to our call to FilePacketConn here: https://sourcegraph.com/github.com/mholt/caddy@fdec3c68f0ba761cff340c78138c5093598b28a5/-/blob/caddy.go#L772

I would expect that calling `Close()` on the `quicServer` would close the `net.PacketConn` we give it.

**Comment by marten-seemann** [comment] 2019-01-28 00:32
This behavior might be unexpected, since it’s different from TCP. In TCP, it’s not possible to run a listener and dialers on the same connection, but in QUIC it is. So you can do the following:
‘’’go
// start listening on a packet conn
server, _ = quic.Listen(pconn, &tls.Config{}, nil)
// dial on THE SAME packet conn
qconn, _ = quic.Dial(pconn, “1.2.3.4:1234”, nil)
// after some time stop accepting new connections...
server.Close()
// the packet conn was NOT closed. qconn can still be used, and you can even dial more connections

**Comment by mholt** [comment] 2019-01-29 19:31
I see... that's interesting. Okay. I reached out to Miek who is the primary maintainer of CoreDNS, which also uses Caddy's UDP serving functionality. Apparently SIGUSR1 works great for CoreDNS.  🤷‍♂️ 

So what do we need to do to ensure that the state gets transferred from the old QUIC server instance to the new one? Maybe this is more about the state of the server than it is about the sockets.

**Comment by mholt** [comment] 2019-01-30 00:39
Looking closer: When we make new HTTP servers, we also make a brand new h2quic Server instance: https://sourcegraph.com/github.com/mholt/caddy@8369a1211544224b2967dd3ac43372a2ef432291/-/blob/caddyhttp/httpserver/server.go#L110:6

We then call Serve anew: https://sourcegraph.com/github.com/mholt/caddy@8369a1211544224b2967dd3ac43372a2ef432291/-/blob/caddyhttp/httpserver/server.go#L345

I feel like this is or should be sufficient to reset the state of the QUIC server.

So now my question is, why does the QUIC server not start over, if a copy of the file descriptor is used to start it? And if the QUIC server "receives a packet with an unexpected connection ID" shouldn't it be able to initiate a new connection instead? I am fairly convinced Caddy is handling the socket properly now, and it's just a matter of wielding the QUIC server instance properly.

**Comment by marten-seemann** [comment] 2019-10-23 02:54
@mholt I believe we resolved this issue a few weeks ago, didn't we? Closing it for now, feel free to reopen if I got this wrong.

**Closed by marten-seemann** 2019-10-23 02:54 UTC

**Comment by mholt** [comment] 2019-10-23 05:17
@marten-seemann Ah, thanks for following up. Sorry, I know the whole thing was a bit confusing.

The last update from me is this comment: https://github.com/caddyserver/caddy/pull/2727#issuecomment-529947251

> To summarize: the issue persists, but by not closing the http3.Server, the issue is either resolved or it hides itself.

So, I can get the symptoms (the errors) to disappear by _not_ closing the http3.Server, however, I am worried this leaks resources. Let me know if it does not (I am not too familiar with the intricacies of `http3.Server.Close()`.

Let me know when the latest draft is supported and a new release is tagged, I will be happy to try it out again and provide another update!

**Comment by marten-seemann** [comment] 2019-10-23 05:30
Makes sense. I'm planning to cut a new quic-go release that (finally!) supports draft-23 some time next week.

**Comment by mholt** [comment] 2019-10-26 18:06
@marten-seemann FWIW, here is currently where we open the HTTP/3 servers:

https://sourcegraph.com/github.com/caddyserver/caddy@2fbe2ff40be616712cf4edaac286629add268e0a/-/blob/modules/caddyhttp/caddyhttp.go#L194-214

And here is where we close them, you can see that some code is commented out:

https://sourcegraph.com/github.com/caddyserver/caddy@2fbe2ff40be616712cf4edaac286629add268e0a/-/blob/modules/caddyhttp/caddyhttp.go#L240-262

Which issue should we track this in?
