### ISSUE TITLE
http3.RoundTripper can only be used for a short time

### ISSUE THREAD

**Issue by folbricht** [lucas-clemente/quic-go#3198] opened 2021-06-05 16:18 UTC
When using http.Client with an http3.RoundTripper, I'm able to make requests as expected. The issue is that if I don't use that client for a while, subsequent requests will fail. Presumably because the underlying connection has timed out. The client doesn't automatically re-open stale connections like the regular http.RoundTripper. What's the correct way to handle this situation with quic? Shouldn't it re-open connections as needed?

Here's an example:

```go
package main

import (
	"log"
	"net/http"
	"time"

	"github.com/lucas-clemente/quic-go"
	"github.com/lucas-clemente/quic-go/http3"
)

func main() {
	roundTripper := &http3.RoundTripper{
		QuicConfig: &quic.Config{
			TokenStore: quic.NewLRUTokenStore(10, 10),
		},
	}

	defer roundTripper.Close()
	hclient := &http.Client{
		Transport: roundTripper,
	}
	log.Println("making first call")
	resp, err := hclient.Get("https://cloudflare-dns.com/dns-query")
	if err != nil {
		log.Fatal(err)
	}
	resp.Body.Close()
	log.Println("got first response")

	time.Sleep(120 * time.Second)

	log.Println("making second call")
	resp, err = hclient.Get("https://cloudflare-dns.com/dns-query")
	if err != nil {
		log.Fatal(err)
	}
	resp.Body.Close()
	log.Println("got second response")
}
```

```
2021/06/05 10:08:19 making first call
2021/06/05 10:08:19 got first response
2021/06/05 10:10:19 making second call
2021/06/05 10:10:19 Get "https://cloudflare-dns.com/dns-query": timeout: no recent network activity
```

In the past I worked around the issue by implementing my own dialer which would re-connect on failure automatically. Unfortunately, in v0.21 of quic, I can no longer call `quic.Session.CloseWithError` as that now requires `qerr.ApplicationErrorCode` which is in an internal package that can't be used from outside the quic package.

**Comment by marten-seemann** [comment] 2021-06-06 06:28
Yes, it should. Duplicate of #765.

**Closed by marten-seemann** 2021-06-06 06:28 UTC
