### ISSUE TITLE
issues with test

### ISSUE THREAD

**Issue by vyrus001** [lucas-clemente/quic-go#532] opened 2017-04-12 21:22 UTC
```
 ~/go/src/github.com/lucas-clemente/quic-go/example/client $ go build
# github.com/lucas-clemente/quic-go/example/client
./main.go:8: imported and not used: "net/http"
./main.go:37: hclient.Get undefined (type *h2quic.Client has no field or method Get)
```
---
go version go1.7.5 linux/amd64

**Comment by marten-seemann** [comment] 2017-04-13 04:24
I can't reproduce. 
Did you run `go get -u ./...` in the root directory?

**Comment by marten-seemann** [comment] 2017-04-16 06:47
Closing this issue now. Feel free to reopen if the problem still occurs.

**Closed by marten-seemann** 2017-04-16 06:47 UTC

**Comment by vyrus001** [comment] 2017-05-01 08:18
yes, i did, stil getting the same errs
