### ISSUE TITLE
why http3 roundTripper.Close() don't wait received the Handshake_DOWN

### ISSUE THREAD

**Issue by ldmid666** [lucas-clemente/quic-go#3316] opened 2022-01-11 03:45 UTC
Hello, I found a problem when I test the http3

the next 0-rtt will fail，if  do not wait for the handshake to complete,

`roundTripper.Close()` code is:

```go
func (c *client) Close() error {
	if c.session == nil {
		return nil
	}
	return c.session.CloseWithError(quic.ApplicationErrorCode(errorNoError), "")
}
```
![image](https://user-images.githubusercontent.com/49946804/149256489-8a944b38-f245-42b1-8ce4-8f3e7075da1c.png)

If I close the connection immediately after I receive the first reply,  the next transfer 0-rtt will fail 。
if I sleep a second  before `roundTripper.Close()` will also 0-rtt success.

```go
	for i < 3 {
			i++
			roundTripper := &http3.RoundTripper{
				TLSClientConfig: &tc,
				QuicConfig: &qconf,
			}
			hclient := &http.Client{
				Transport: roundTripper,
			}
			req, err := http.NewRequest(http3.MethodGet0RTT, url, nil) 
			_, err = hclient.Do(req)
			if err != nil {
				log.Fatal(err)
			}
			// print body
			fmt.Println("need to wait for the handshake_done before closing")
			time.Sleep(1*time.Second) // need wait one rtt for handshake
			roundTripper.Close()
	}
```

I found some solutions to wait handshake confirmed：

https://github.com/kaiyuhou/quic-go-v201/blob/c5310f35c799cdbe226c2901effca5f260d36610/http3/roundtrip.go#L186
![image](https://user-images.githubusercontent.com/49946804/148878050-1f44bed1-2a6a-42c6-b9b0-1258c5ca33ac.png)

@kaiyuhou Can you tell me why?

why http3.RoundTripper.close() not support wait handshake confirmed?

**Comment by NitroCao** [comment] 2022-01-12 11:19
( May I ask which tool you use to generate the graph? )

**Comment by ldmid666** [comment] 2022-01-12 11:23
https://qvis.quictools.info/#/sequence @NitroCao

**Comment by marten-seemann** [comment] 2022-01-12 17:40
I don't understand this issue. What's the problem?

**Comment by ldmid666** [comment] 2022-01-13 02:37
> I don't understand this issue. What's the problem?
@marten-seemann  hi, When I test the http3 0-rtt，
I found I need to wait for the handshake to complete before closing, otherwise the next can not usr 0-rtt

```go
	for i < 3 {
			i++
			roundTripper := &http3.RoundTripper{
				TLSClientConfig: &tc,
				QuicConfig: &qconf,
			}
			hclient := &http.Client{
				Transport: roundTripper,
			}
			req, err := http.NewRequest(http3.MethodGet0RTT, url, nil) 
			_, err = hclient.Do(req)
			if err != nil {
				log.Fatal(err)
			}
			// print body
			fmt.Println("need to wait for the handshake_done before closing")
			time.Sleep(1*time.Second) // need wait one rtt for handshake
			roundTripper.Close()
	}
```

**Comment by kaiyuhou** [comment] 2022-01-14 06:52
Hi @ldmid666 , I am so surprised that you find my solution to this issue! You can use this diff to solve your problem if you just want to find a hack solution to mitigate this problem. The solution is simple and straightforward: https://github.com/kaiyuhou/quic-go-v201/commit/c16996205e73c9591fd5ce7033ab528d055b3f1b

Hi, @marten-seemann let me explain this issue to you:
- When the client sends out the 0-RTT `request`, it will use pre-cached `QUIC 0-RTT Token` and `TLS Session Ticket` to resume the connection and encrypt the `request` packet. 
  - (Then the pre-cached `QUIC 0-RTT Token` and `TLS Session Ticket` will auto expired.) 
- The server will **immediately** send back the `response` data packet. 
- Ideally, the client will send `Handshake_Finished` to the server, and the server will send back `Handshake_Done`. 
  - The `Handshake_Done` will carry a new `QUIC 0-RTT Token` and `TLS Session Ticket`, which can be used for the next 0-RTT connection.
- **But**, in current quic-go implementation, after the application (i.e., HTTP/3 client) received the `response` data, it will call the `defer roundTripper.Close()`. 
  - **The QUIC client will directly send a `Connection_Clone (Application)` to the server and close the QUIC session.**
  - So, it has no chance to receive the new `QUIC 0-RTT Token` and `TLS Session Ticket`.
- Therefore, the next connection will fall back to 1-RTT. 
  - So, in this case, **a success 0-RTT connection will always be followed by a failed 0-RTT, and then a success 0-RTT**. 
- Will the application has the ability to solve this issue? I think No. Because the application doesn't have detailed information about the underline QUIC handshake status. So, it has to be solved at the QUIC level.

I am not sure whether QUIC RFC mentioned this or the current design choice in quic-go is an RFC undefined behavior. But I would think the current design choice is reasonable. 

If the client doesn't care about the potential next 0-RTT session assumption performance, the client has no reason to keep the current connection, waiting for the `Handshake_Done` message from the server, if the client has already received the `response` data.

But I am now thinking, if it does not violate the RFC, it may be worth adding the functionality of my `roundTripper.closeAfterHandshakeConfirmed()` function as a option to the `roundTripper.Close()` function. I do need it to solve my scenarios when using quic-go since half a year ago. And now we find another person who wants it.

**Comment by marten-seemann** [comment] 2022-01-14 07:07
Thank you for the detailed explanation.

> Will the application has the ability to solve this issue? I think No. Because the application doesn't have detailed information about the underline QUIC handshake status. So, it has to be solved at the QUIC level.

What about `EarlySession.HandshakeComplete`?

But really, there's no requirement on the server to immediately send a new token and a new session ticket (this has nothing to do with HANDSHAKE_DONE, btw). quic-go (currently) does so, but that's an implementation decision and might change at some point in the future.
If you want to guarantee that the next connection attempt will be able to use 0-RTT, you'll probably want to monitor your TLS session ticket cache.

**Comment by kaiyuhou** [comment] 2022-01-14 07:28
For *immediately*, I mean the server will immediately send back the application response. So, it will come faster than the `Handshake_Down` message, which raises this issue.

I like your idea of monitoring the TLS session ticket cache at the application level.
- BTW, the current [http3 client example](https://github.com/lucas-clemente/quic-go/blob/master/example/client/main.go) is a little simple. It doesn't show users how to create QUIC TokenStore and TLS ClientSessionCache, and the correct way to enable 0-RTT. 

For `EarlySession.HandshakeComplete`, is there a way for the application to access it?

**Comment by marten-seemann** [comment] 2022-01-14 07:31
> For immediately, I mean the server will immediately send back the application response. So, it will come faster than the Handshake_Down message, which raises this issue.

That is the correct behavior. You want the server to send the response as quickly as possible. Otherwise, 0-RTT would be kind of pointless.

> For EarlySession.HandshakeComplete, is there a way for the application to access it?

Not sure if there's a way to get it from http3. I don't see a strong use case, tbh. It's used internally, for all requests that don't use 0-RTT.

**Comment by ldmid666** [comment] 2022-01-14 08:26
> * BTW, the current [http3 client example](https://github.com/lucas-clemente/quic-go/blob/master/example/client/main.go) is a little simple. It doesn't show users how to create QUIC TokenStore and TLS ClientSessionCache, and the correct way to enable 0-RTT.

@kaiyuhou Thank you for the detailed explanation.  @marten-seemann  I also found another problem about 0-rtt example. I refer to your code `zero_rtt_test.go`. 
https://github.com/lucas-clemente/quic-go/blob/8ecbb05d446ae3aef199f8ad50678d637ec95eb3/integrationtests/self/zero_rtt_test.go#L91

```go
    gets := make(chan string, 100)
    puts := make(chan string, 100)
    clientConf.ClientSessionCache = newClientSessionCache(gets, puts)
```
I found  the `SessionCache` must be a LRU cache. Otherwise, it will be blocked  (to write new?).

**Comment by marten-seemann** [comment] 2022-01-14 08:28
`ClientSessionCache` is an interface, you're free to use any implementation of that interface you like.

**Comment by marten-seemann** [comment] 2022-01-14 08:28
I think we've resolved the issue here. Closing this.

**Closed by marten-seemann** 2022-01-14 08:28 UTC
