### ISSUE TITLE
close connection when using DialAddr

### ISSUE THREAD

**Issue by phifty** [lucas-clemente/quic-go#1457] opened 2018-07-17 12:22 UTC
I'm using Go 1.10.1 and quic-go v0.8.0. My setup is quite simple: a client opens a session with `quic.DialAddrContext` and a single stream, transfers data and closes both with `stream.Close()` and `session.Close(nil)`.
It seems that after the `Close` a goroutine and also a socket stays alive. Via the profiling interface, a huge number of goroutines with the following stack trace occurs:

    # 0x4274f6 internal/poll.runtime_pollWait+0x56 /nix/store/g26fjzz20rydrbylmlf8hiidxycazbys-go-1.10.1/share/go/src/runtime/netpoll.go:173
    # 0x4932ca internal/poll.(*pollDesc).wait+0x9a /nix/store/g26fjzz20rydrbylmlf8hiidxycazbys-go-1.10.1/share/go/src/internal/poll/fd_poll_runtime.go:85
    # 0x49334c internal/poll.(*pollDesc).waitRead+0x3c /nix/store/g26fjzz20rydrbylmlf8hiidxycazbys-go-1.10.1/share/go/src/internal/poll/fd_poll_runtime.go:90
    # 0x4945bc internal/poll.(*FD).ReadFrom+0x17c /nix/store/g26fjzz20rydrbylmlf8hiidxycazbys-go-1.10.1/share/go/src/internal/poll/fd_unix.go:207
    # 0x5cfe8a net.(*netFD).readFrom+0x5a /nix/store/g26fjzz20rydrbylmlf8hiidxycazbys-go-1.10.1/share/go/src/net/fd_unix.go:208
    # 0x5ef449 net.(*UDPConn).readFrom+0x69 /nix/store/g26fjzz20rydrbylmlf8hiidxycazbys-go-1.10.1/share/go/src/net/udpsock_posix.go:47
    # 0x5ecf1e net.(*UDPConn).ReadFrom+0x6e /nix/store/g26fjzz20rydrbylmlf8hiidxycazbys-go-1.10.1/share/go/src/net/udpsock.go:118
    # 0x9ec835 .../vendor/github.com/lucas-clemente/quic-go.(*conn).Read+0x55 /.../vendor/github.com/lucas-clemente/quic-go/conn.go:32
    # 0x9ea95f .../vendor/github.com/lucas-clemente/quic-go.(*client).listen+0x9f /.../vendor/github.com/lucas-clemente/quic-go/client.go:330

I'm not sure if I missed something, but it seems like a bug in the quic-go lib.
Any help is appreciated.
Best regards

**Comment by marten-seemann** [comment] 2018-07-17 20:43
Thanks for reporting this!

We never stop listening on the connection until a `Read` call on the connection fails. This is the intended behaviour when using `Dial` (where you pass in a `net.PacketConn`), but not correct for `DialAddr` (which creates a new `net.PacketConn`).
As far as I can see, this should only result in a single go routine staying alive after closing the session though.

**Comment by phifty** [comment] 2018-07-18 08:37
You're welcome! And many thanks for the quick reply.

If I'm using `Dial` instead of `DialAddr` and create a custom `net.PacketConn` which I can close after stream and session, the corresponding goroutine should terminate and the leak should be gone? Or am I missing something?

The background is, that I'm using this quic implementation in `github.com/simia-tech/netx`. It comes with a simple load balancer that opens and closes many connections. The bug causes than a shortage of open files on the system.

**Comment by marten-seemann** [comment] 2018-07-18 09:56
Yes, that should work until we fix that issue.

**Comment by phifty** [comment] 2018-07-18 11:59
Hmm... I've tried the workaround, but the goroutine still seems to hang around. See the implementation at https://github.com/simia-tech/netx/blob/master/network/quic/conn.go

But I'll do further testing.

**Comment by marten-seemann** [comment] 2018-07-18 13:34
The `listen` go routine should return as soon as the `ReadFrom` fails, see https://github.com/lucas-clemente/quic-go/blob/master/client_multiplexer.go#L87-L106.
Please let me know if that doesn't work as intended.

**Closed** 2018-08-08 02:47 UTC
Labels: bug
