### ISSUE TITLE
example client and server don't work using -tls option for IETF QUIC

### ISSUE THREAD

**Issue by fabiobu** [lucas-clemente/quic-go#1463] opened 2018-07-31 09:43 UTC
Using -tls option on both server and client an Handshake error is returned (0x1c - Access denied).
Without -tls option, so in gQUIC mode, they work without problem.

**Client Log:**
GET https://localhost:6121/demo/tile
client Starting new connection to localhost ([::]:55827 -> 127.0.0.1:6121), source connection ID 0xe055ee14, destination connection ID 0x7beada02255349a02a0921ca9bc634468269, version TLS dev version (WIP)
client Closing session with error: closing session in order to recreate after a retry
client Connection 0xe055ee14 closed.
client Received a Retry packet. Recreating session.
client Queueing packet 0x1 for later decryption
client Queueing packet 0x1 for later decryption
client Queueing packet 0x1 for later decryption
client Queueing packet 0x1 for later decryption
client Queueing packet 0x1 for later decryption
client Queueing packet 0x1 for later decryption
client Closing session with error: HandshakeTimeout: Crypto handshake did not complete in time.
client Connection 0xe055ee14 closed.
panic: Get https://localhost:6121/demo/tile: HandshakeTimeout: Crypto handshake did not complete in time.

**Server Log:**
server Listening for udp connections on 127.0.0.1:6121
server Received a Packet. Handling it statelessly.
server <- Reading packet 0x1 (1200 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269
server 	Long Header{Type: Initial, DestConnectionID: 0x7beada02255349a02a0921ca9bc634468269, SrcConnectionID: 0xe055ee14, PacketNumber: 0x1, PacketNumberLen: 2, PayloadLen: 1168, Version: TLS dev version (WIP)}
server 	<- &wire.StreamFrame{StreamID: 0, FinBit: false, Offset: 0x0, Data length: 0x27d, Offset + Data length: 0x27d}
server Received Transport Parameters: &handshake.TransportParameters{StreamFlowControlWindow: 0x8000, ConnectionFlowControlWindow: 0xc000, MaxBidiStreams: 100, MaxUniStreams: 100, IdleTimeout: 30s}
server -> Sending packet 0x1 (246 bytes) for connection 0x7333466e, unencrypted
server 	Long Header{Type: Retry, DestConnectionID: 0xe055ee14, SrcConnectionID: 0x7333466e, PacketNumber: 0x1, PacketNumberLen: 2, PayloadLen: 228, Version: TLS dev version (WIP)}
server 	-> &wire.StreamFrame{StreamID: 0, FinBit: false, Offset: 0x0, Data length: 0xd2, Offset + Data length: 0xd2}
server Received a Packet. Handling it statelessly.
server <- Reading packet 0x1 (1200 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269
server 	Long Header{Type: Initial, DestConnectionID: 0x7beada02255349a02a0921ca9bc634468269, SrcConnectionID: 0xe055ee14, PacketNumber: 0x1, PacketNumberLen: 2, PayloadLen: 1168, Version: TLS dev version (WIP)}
server 	<- &wire.StreamFrame{StreamID: 0, FinBit: false, Offset: 0x0, Data length: 0x316, Offset + Data length: 0x316}
server Received Transport Parameters: &handshake.TransportParameters{StreamFlowControlWindow: 0x8000, ConnectionFlowControlWindow: 0xc000, MaxBidiStreams: 100, MaxUniStreams: 100, IdleTimeout: 30s}
server -> Sending packet 0x1 (63 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269, unencrypted
server 	Long Header{Type: Handshake, DestConnectionID: 0xe055ee14, SrcConnectionID: 0x7beada02255349a02a0921ca9bc634468269, PacketNumber: 0x1, PacketNumberLen: 1, PayloadLen: 0, Version: TLS dev version (WIP)}
server 	-> &wire.ConnectionCloseFrame{ErrorCode:0x1c, ReasonPhrase:"access denied"}
server Error occurred handling initial packet: access denied
server Received a Packet. Handling it statelessly.
server <- Reading packet 0x2 (1200 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269
server 	Long Header{Type: Initial, DestConnectionID: 0x7beada02255349a02a0921ca9bc634468269, SrcConnectionID: 0xe055ee14, PacketNumber: 0x2, PacketNumberLen: 2, PayloadLen: 1168, Version: TLS dev version (WIP)}
server 	<- &wire.StreamFrame{StreamID: 0, FinBit: false, Offset: 0x0, Data length: 0x316, Offset + Data length: 0x316}
server Received Transport Parameters: &handshake.TransportParameters{StreamFlowControlWindow: 0x8000, ConnectionFlowControlWindow: 0xc000, MaxBidiStreams: 100, MaxUniStreams: 100, IdleTimeout: 30s}
server -> Sending packet 0x1 (63 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269, unencrypted
server 	Long Header{Type: Handshake, DestConnectionID: 0xe055ee14, SrcConnectionID: 0x7beada02255349a02a0921ca9bc634468269, PacketNumber: 0x1, PacketNumberLen: 1, PayloadLen: 0, Version: TLS dev version (WIP)}
server 	-> &wire.ConnectionCloseFrame{ErrorCode:0x1c, ReasonPhrase:"access denied"}
server Error occurred handling initial packet: access denied
server Received a Packet. Handling it statelessly.
server <- Reading packet 0x3 (1200 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269
server 	Long Header{Type: Initial, DestConnectionID: 0x7beada02255349a02a0921ca9bc634468269, SrcConnectionID: 0xe055ee14, PacketNumber: 0x3, PacketNumberLen: 2, PayloadLen: 1168, Version: TLS dev version (WIP)}
server 	<- &wire.StreamFrame{StreamID: 0, FinBit: false, Offset: 0x0, Data length: 0x316, Offset + Data length: 0x316}
server Received Transport Parameters: &handshake.TransportParameters{StreamFlowControlWindow: 0x8000, ConnectionFlowControlWindow: 0xc000, MaxBidiStreams: 100, MaxUniStreams: 100, IdleTimeout: 30s}
server -> Sending packet 0x1 (63 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269, unencrypted
server 	Long Header{Type: Handshake, DestConnectionID: 0xe055ee14, SrcConnectionID: 0x7beada02255349a02a0921ca9bc634468269, PacketNumber: 0x1, PacketNumberLen: 1, PayloadLen: 0, Version: TLS dev version (WIP)}
server 	-> &wire.ConnectionCloseFrame{ErrorCode:0x1c, ReasonPhrase:"access denied"}
server Error occurred handling initial packet: access denied
server Received a Packet. Handling it statelessly.
server <- Reading packet 0x4 (1200 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269
server 	Long Header{Type: Initial, DestConnectionID: 0x7beada02255349a02a0921ca9bc634468269, SrcConnectionID: 0xe055ee14, PacketNumber: 0x4, PacketNumberLen: 2, PayloadLen: 1168, Version: TLS dev version (WIP)}
server 	<- &wire.StreamFrame{StreamID: 0, FinBit: false, Offset: 0x0, Data length: 0x316, Offset + Data length: 0x316}
server Received Transport Parameters: &handshake.TransportParameters{StreamFlowControlWindow: 0x8000, ConnectionFlowControlWindow: 0xc000, MaxBidiStreams: 100, MaxUniStreams: 100, IdleTimeout: 30s}
server -> Sending packet 0x1 (63 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269, unencrypted
server 	Long Header{Type: Handshake, DestConnectionID: 0xe055ee14, SrcConnectionID: 0x7beada02255349a02a0921ca9bc634468269, PacketNumber: 0x1, PacketNumberLen: 1, PayloadLen: 0, Version: TLS dev version (WIP)}
server 	-> &wire.ConnectionCloseFrame{ErrorCode:0x1c, ReasonPhrase:"access denied"}
server Error occurred handling initial packet: access denied
server Received a Packet. Handling it statelessly.
server <- Reading packet 0x5 (1200 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269
server 	Long Header{Type: Initial, DestConnectionID: 0x7beada02255349a02a0921ca9bc634468269, SrcConnectionID: 0xe055ee14, PacketNumber: 0x5, PacketNumberLen: 2, PayloadLen: 1168, Version: TLS dev version (WIP)}
server 	<- &wire.StreamFrame{StreamID: 0, FinBit: false, Offset: 0x0, Data length: 0x316, Offset + Data length: 0x316}
server Received Transport Parameters: &handshake.TransportParameters{StreamFlowControlWindow: 0x8000, ConnectionFlowControlWindow: 0xc000, MaxBidiStreams: 100, MaxUniStreams: 100, IdleTimeout: 30s}
server -> Sending packet 0x1 (63 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269, unencrypted
server 	Long Header{Type: Handshake, DestConnectionID: 0xe055ee14, SrcConnectionID: 0x7beada02255349a02a0921ca9bc634468269, PacketNumber: 0x1, PacketNumberLen: 1, PayloadLen: 0, Version: TLS dev version (WIP)}
server 	-> &wire.ConnectionCloseFrame{ErrorCode:0x1c, ReasonPhrase:"access denied"}
server Error occurred handling initial packet: access denied
server Received a Packet. Handling it statelessly.
server <- Reading packet 0x6 (1200 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269
server 	Long Header{Type: Initial, DestConnectionID: 0x7beada02255349a02a0921ca9bc634468269, SrcConnectionID: 0xe055ee14, PacketNumber: 0x6, PacketNumberLen: 2, PayloadLen: 1168, Version: TLS dev version (WIP)}
server 	<- &wire.StreamFrame{StreamID: 0, FinBit: false, Offset: 0x0, Data length: 0x316, Offset + Data length: 0x316}
server Received Transport Parameters: &handshake.TransportParameters{StreamFlowControlWindow: 0x8000, ConnectionFlowControlWindow: 0xc000, MaxBidiStreams: 100, MaxUniStreams: 100, IdleTimeout: 30s}
server -> Sending packet 0x1 (63 bytes) for connection 0x7beada02255349a02a0921ca9bc634468269, unencrypted
server 	Long Header{Type: Handshake, DestConnectionID: 0xe055ee14, SrcConnectionID: 0x7beada02255349a02a0921ca9bc634468269, PacketNumber: 0x1, PacketNumberLen: 1, PayloadLen: 0, Version: TLS dev version (WIP)}
server 	-> &wire.ConnectionCloseFrame{ErrorCode:0x1c, ReasonPhrase:"access denied"}
server Error occurred handling initial packet: access denied
server Received Handshake packet for unknown connection 0x7beada02255349a02a0921ca9bc634468269.

**Comment by marten-seemann** [comment] 2018-07-31 09:52
Closing as a duplicate of #1453 and #1366 and many others.

**Closed by marten-seemann** 2018-07-31 09:52 UTC
