### ISSUE TITLE
Server's ReadFrom(stream) returning TooManyOpenStreams

### ISSUE THREAD

**Issue by Arceliar** [lucas-clemente/quic-go#954] opened 2017-11-21 20:16 UTC
I'm not sure if this is a bug, or if I just don't understand the intended behavior, but I'm getting `TooManyOpenStreams` errors in cases where I did not expect them.

When running a client and server, with a client that opens a very large number of streams, I use `OpenStreamSync()` on the client to block until a stream is ready. So far, I haven't seen any problems with the client.

On the server side, I `AcceptStream()` without error. Then when the server tries to `ReadFrom(stream)`, it returns a `TooManyOpenStreams` error. I would have expected the server to block on `AcceptStream()` until the number of streams was low enough to accept a new one. Failing that, I would have at least expected the `TooManyOpenStreams` error to happen on `AcceptStream()`, instead of coming from `ReadFrom(stream)`.

The below example is sufficient to trigger the problem on my machine (but I suspect it could require increasing msgCount and/or msgSize on a faster machine).

```
package main

import (
  "fmt"
  "time"
  "bytes"
  "sync"
  "crypto/rand"
  "crypto/rsa"
  "crypto/tls"
  "crypto/x509"
  "encoding/pem"
  "math/big"
  quic "github.com/lucas-clemente/quic-go"
)

const addr = "[::1]:9001"

func main () {
  go run_server()
  run_client()
}

func run_server() {
  listener, err := quic.ListenAddr(addr, generateTLSConfig(), nil)
  if err != nil { panic(err) }
  ses, err := listener.Accept()
  if err != nil { panic(err) }
  for {
    stream, err := ses.AcceptStream()
    if err != nil { panic(err) }
    go func() {
      defer stream.Close()
      bs := bytes.Buffer{}
      _, err := bs.ReadFrom(stream)
      if err != nil { panic(err) } //<-- TooManyOpenStreams
    }()
  }
}

func run_client() {
  msgSize := 1048576
  msgCount := 128
  ses, err := quic.DialAddr(addr, &tls.Config{InsecureSkipVerify: true}, nil)
  if err != nil { panic(err) }
  bs := make([]byte, msgSize)
  wg := sync.WaitGroup{}
  start := time.Now()
  for idx := 0 ; idx < msgCount ; idx++ {
    wg.Add(1)
    go func() {
      defer wg.Done()
      stream, err := ses.OpenStreamSync()
      if err != nil { panic(err) }
      defer stream.Close()
      stream.Write(bs)
    }() // If I don't "go" this then it's fine
  }
  wg.Wait()
  timed := time.Since(start)
  fmt.Println("Client finished", timed, fmt.Sprintf("%f Bits/sec", 8*float64(msgSize*msgCount)/timed.Seconds()))  
}

// Setup a bare-bones TLS config for the server
func generateTLSConfig() *tls.Config {
	key, err := rsa.GenerateKey(rand.Reader, 1024)
	if err != nil {
		panic(err)
	}
	template := x509.Certificate{SerialNumber: big.NewInt(1)}
	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		panic(err)
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)})
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDER})

	tlsCert, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		panic(err)
	}
	return &tls.Config{Certificates: []tls.Certificate{tlsCert}}
}

```

**Comment by marten-seemann** [comment] 2017-11-22 20:08
Hello @Arceliar,

unfortunately, this is not a bug in quic-go, but an issue with the QUIC protocol itself. In the current version of QUIC, this is a nasty corner case. The definition of open streams is inherently racy between the two peers (a peer that just closed a stream will regard this stream as closed, whereas the other peer will regard it as open until it received the corresponding FIN bit). There's a "margin of safety" to account for this raciness (https://github.com/lucas-clemente/quic-go/blob/master/internal/protocol/server_parameters.go#L62-L66), which was chosen for the HTTP use case, and might not be sufficient if you have many short-lived streams.

Note that this will change when quic-go moves closer go IETF QUIC (we're tracking Chrome, which is kind of slow adopting the draft changes, so this will likely take a couple of months) with the introduction of the MAX_STREAM_ID frame: https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.8.8 (#878 is tracking this)

I wish I could give you a better answer, but the only thing that reliably "works" for the current QUIC version is staying below the max stream limit. You can also try adjusting the margin of safety or increasing the max stream limit.

**Comment by marten-seemann** [comment] 2017-12-04 02:38
@Arceliar: I'm closing this issue now, since there's nothing we can do about this at the current moment. Feel free to reopen (or open a new issue) if you have any further questions.

**Closed by marten-seemann** 2017-12-04 02:38 UTC
