### ISSUE TITLE
Lower average latency than TCP

### ISSUE THREAD

**Issue by sarsanaee** [lucas-clemente/quic-go#1497] opened 2018-08-25 16:55 UTC
Hi, 

I was playing with the echo example application in the codebase and have a latency comparison between a simple TCP socket application in Go. I noticed that the average latency in TCP is variable between 50 to 200 microseconds but in QUIC Go echo application the latency is variable between 300 to 500 microseconds or more! Actually, QUIC go is 2x slower and more variable! Is this expected?

Thanks

**Comment by marten-seemann** [comment] 2018-08-26 01:07
I'm not really worried about latency in the microsecond range. QUIC is designed to be beneficial to real-world connections, not transfers to localhost.
Feel free to debug this a bit further, we'd be happy to merge any fixes for this, if you can find the cause of the problem.

**Comment by sarsanaee** [comment] 2018-08-26 07:55
I was thinking that QUIC protocol can be used for data center applications. When I send a request to the Google servers, then my request to be responded requires some communications among multiple servers at the data center which is LAN communication. There may be a couple of servers connected to each other via a Top of the Rack 10G switch involved in the process of responding to a request. It seems that data center communications are TCP based so far and I thought there might be interesting to have a comparison between them.

Do you think that this case I described is valid at all?!

Thanks

**Comment by marten-seemann** [comment] 2018-08-26 08:07
You can use it for that, and I know there are people who are thinking about data center usage of QUIC. 
However, the main benefits of QUIC are the lack of HoL between streams (which comes into play when packets are lost), and the better loss recovery.

**Comment by marten-seemann** [comment] 2018-09-07 05:49
Closing this issue. Feel free to open a new one if you have any more questions.

**Closed by marten-seemann** 2018-09-07 05:49 UTC
