### ISSUE TITLE
Problem closing streams

### ISSUE THREAD

**Issue by Stebalien** [lucas-clemente/quic-go#1811] opened 2019-03-06 02:18 UTC
I noticed that go-ipfs is getting stuck on shutdown when quic has been running for a long time. It looks like there's some kind of stream closing deadlock:

```
goroutine 536437 [semacquire, 209 minutes]:
sync.runtime_SemacquireMutex(0xc0099f53a8, 0x9fd500)
        /usr/lib/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0099f53a4)
        /usr/lib/go/src/sync/mutex.go:134 +0xff
gx/ipfs/QmU44KWVkSHno7sNDTeUcL4FBgxgoidkFuTUyTXWJPXXFJ/quic-go.(*streamFramer).AddActiveStream(0xc0099f5380, 0x61)
        /home/steb/projects/go/src/gx/ipfs/QmU44KWVkSHno7sNDTeUcL4FBgxgoidkFuTUyTXWJPXXFJ/quic-go/stream_framer.go:41 +0x5d
gx/ipfs/QmU44KWVkSHno7sNDTeUcL4FBgxgoidkFuTUyTXWJPXXFJ/quic-go.(*session).onHasStreamData(0xc0015f3800, 0x61)
        /home/steb/projects/go/src/gx/ipfs/QmU44KWVkSHno7sNDTeUcL4FBgxgoidkFuTUyTXWJPXXFJ/quic-go/session.go:1263 +0x3c
gx/ipfs/QmU44KWVkSHno7sNDTeUcL4FBgxgoidkFuTUyTXWJPXXFJ/quic-go.(*uniStreamSender).onHasStreamData(0xc000957240, 0x61)
        /home/steb/projects/go/src/gx/ipfs/QmU44KWVkSHno7sNDTeUcL4FBgxgoidkFuTUyTXWJPXXFJ/quic-go/stream.go:38 +0x3d
gx/ipfs/QmU44KWVkSHno7sNDTeUcL4FBgxgoidkFuTUyTXWJPXXFJ/quic-go.(*sendStream).Close(0xc010d6f5e8, 0x0, 0x0)
        /home/steb/projects/go/src/gx/ipfs/QmU44KWVkSHno7sNDTeUcL4FBgxgoidkFuTUyTXWJPXXFJ/quic-go/send_stream.go:219 +0x163
gx/ipfs/QmU44KWVkSHno7sNDTeUcL4FBgxgoidkFuTUyTXWJPXXFJ/quic-go.(*stream).Close(0xc010d6f520, 0xc0098c6900, 0x1042fb6)
        /home/steb/projects/go/src/gx/ipfs/QmU44KWVkSHno7sNDTeUcL4FBgxgoidkFuTUyTXWJPXXFJ/quic-go/stream.go:135 +0x34
gx/ipfs/Qma3Xp3FXFSP4prirEiRYHJ2tgGE8EAx9i6JLziPLpAQjq/go-libp2p-swarm.(*Stream).Close(0xc0009f8d70, 0x0, 0xc000c33dc8)
        /home/steb/projects/go/src/gx/ipfs/Qma3Xp3FXFSP4prirEiRYHJ2tgGE8EAx9i6JLziPLpAQjq/go-libp2p-swarm/swarm_stream.go:100 +0x37
gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio.(*reader).Close(0xc00bf03040, 0xc00a814d01, 0x1a9d3c0)
        /home/steb/projects/go/src/gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio/msgio.go:217 +0x5e
gx/ipfs/QmSVaJe1aRjc78cZARTtf4pqvXERYwihyYhZWoVWceHnsK/go-libp2p-secio.(*etmReader).Close(0xc0007b92c0, 0x601e685a6078, 0xc0007b92c0)
        /home/steb/projects/go/src/gx/ipfs/QmSVaJe1aRjc78cZARTtf4pqvXERYwihyYhZWoVWceHnsK/go-libp2p-secio/rw.go:240 +0x34
gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio.(*readWriter).Close(0xc000aba040, 0xc00bf77200, 0xc00a7c7e58)
        /home/steb/projects/go/src/gx/ipfs/QmcxL9MDzSU5Mj1GcWZD8CXkAFuJXjdbjotZ93o371bKSf/go-msgio/msgio.go:251 +0x124
gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux.(*Session).Close(0xc00bc149c0, 0x0, 0x0)
        /home/steb/projects/go/src/gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux/session.go:252 +0xd7
gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux.(*Session).exitErr(0xc00bc149c0, 0x1a70e60, 0xc0000a4030)
        /home/steb/projects/go/src/gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux/session.go:272 +0x68
gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux.(*Session).recv(0xc00bc149c0)
        /home/steb/projects/go/src/gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux/session.go:515 +0x4b
created by gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux.newSession
        /home/steb/projects/go/src/gx/ipfs/QmUNMbRUsVYHi1D14annF7Rr7pQAX7TNLwpRCa975ojKnw/yamux/session.go:128 +0x386
```

Full: https://gist.github.com/5e4834f0eb746cd1149392e06f208c24

**Comment by marten-seemann** [comment] 2019-03-06 02:25
Probably a duplicate of #1364, which was fixed long time ago. We should roll out an update to go-libp2p-quic-transport.

**Closed** 2019-03-06 05:32 UTC
Labels: duplicate
