### ISSUE TITLE
Stream exhaustion in h2quic client

### ISSUE THREAD

**Issue by chaehni** [lucas-clemente/quic-go#1618] opened 2018-11-21 13:43 UTC
I'm building an application with the ```h2quic.Server``` and ```h2quic.RoundTripper```.  My application has a benchmarking mode where it sends continuous requests to the server. Since ```h2quic.RoundTripper``` caches connections to the same host, it opens a new stream in the same session for every request sent. This makes the client run into a ```NetworkIdleTimeout: No recent network activity``` error after the ```DefaultMaxIncomingStreams``` of size 100 is reached. Any subsequent requests time out and return this error. It appears to me that the opened streams don't get closed after the response was received.

**Comment by marten-seemann** [comment] 2018-11-25 04:30
Hello @chaehni, I tried to reproduce the problem, but everything seems to work here.
To reproduce, I'm running the [example server](https://github.com/lucas-clemente/quic-go/blob/master/example/main.go). For making the request, I modified the example client to make 200 requests. Here's the code: https://gist.github.com/marten-seemann/71fb9aece5943998f334d999bb713703. The client completes the 200 requests in less than a second, and without any error.

Could you post a minimum working example that exhibits the problem?

**Comment by chaehni** [comment] 2018-11-25 16:41
Hello @marten-seemann, thank you for looking into this.
I created a minimum working example: https://gist.github.com/chaehni/5bd3a7f1b614f291456a303571e7a6b6

I receive the following output: 
```
GET request 0 succeeded
...
GET request 98 succeeded
```
However, now I don't get `NetworkIdleTimeout: No recent network activity` for request 99 anymore. It just seems to run indefinitely.
The only difference to your example I can see is the added `TLSClientConfig` in the RoundTripper.

**Comment by marten-seemann** [comment] 2018-11-26 01:07
I haven't run the code, but it seems like you're not closing the response body (the `defer` in https://gist.github.com/chaehni/5bd3a7f1b614f291456a303571e7a6b6#file-client-go-L31 is only executed after `main()` returns...). Does that fix your problem?

**Comment by marten-seemann** [comment] 2018-11-28 01:31
It seems like the h2quic implementation differs from what the Go standard library HTTP/2 implementation is doing:
https://github.com/golang/net/blob/adae6a3d119ae4890b46832a2e88a95adc62b8e7/http2/transport.go#L1917-L1919

If we want to close the response body there seem to be two cases to consider:

1. The server already closed the stream, and sent the EOF. In that case, h2quic needs to drain the response first.
2. The server is still sending the response. In that case, we need to reset the stream by calling `CancelRead` on that stream. The transport will send a STOP_SENDING and the server will send a RST_STREAM on the stream (the transport needs the RST_STREAM to learn about the final stream offset, to do the connection flow control accounting). h2quic then need to read until reading fails an error.

The problem I see here is that 2. takes one RTT, and we probably don't want to block `Close()` on that. This suggests that resetting the stream should happen in a separate Go routine.

@chaehni, does that sound right to you?

**Comment by chaehni** [comment] 2018-11-29 17:29
@marten-seemann yes, that looks good to me.

**Comment by marten-seemann** [comment] 2018-12-28 10:57
I just started working on a fix, and noticed that the problem is not a **stream** exhaustion, but a **flow control** exhaustion.
This is because the HTTP data stream is a client initiated stream, which in case of a GET request is immediately closed by the client. The server closes the stream after writing the response, so it can remove the stream from its map, and grant the client new stream IDs.

**Closed** 2019-01-23 14:15 UTC
Labels: bug
