### ISSUE TITLE
caddy with quic-go v.0.10.1 crashes regularly

### ISSUE THREAD

**Issue by stephanreiter** [lucas-clemente/quic-go#1786] opened 2019-02-13 02:26 UTC
Hi!

Since I upgraded caddy to the latest version, I see it crashing regularly with the following callstack:

```
Feb 10 12:02:16 webhost caddy[27369]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 10 12:02:16 webhost caddy[27369]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8e21cc]
Feb 10 12:02:16 webhost caddy[27369]: goroutine 1785 [running]:
Feb 10 12:02:16 webhost caddy[27369]: github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto.(*certChain).getCertForSNI(0xc00000c910, 0xc00046b690, 0xd, 0xc0006dcea0, 0xc0ab214, 0xf5d823d5d2e10447)
Feb 10 12:02:16 webhost caddy[27369]: #011/tmp/gopath_01-16-2336.857153519/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go:66 +0x6c
Feb 10 12:02:16 webhost caddy[27369]: github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto.(*certChain).GetLeafCert(0xc00000c910, 0xc00046b690, 0xd, 0xc0001f86f8, 0xc00046b601, 0xd, 0xc0006dcf90, 0x10)
Feb 10 12:02:16 webhost caddy[27369]: #011/tmp/gopath_01-16-2336.857153519/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go:51 +0x43
Feb 10 12:02:16 webhost caddy[27369]: github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetupServer).handleMessage(0xc00021dcc0, 0xc000414e00, 0x514, 0x60f, 0xc00009a990, 0x1, 0xcc7de0, 0xc00004c820)
Feb 10 12:02:16 webhost caddy[27369]: #011/tmp/gopath_01-16-2336.857153519/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup_server.go:162 +0x18f
Feb 10 12:02:16 webhost caddy[27369]: github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetupServer).HandleCryptoStream(0xc00021dcc0, 0x45bca6, 0xbfd39c)
Feb 10 12:02:16 webhost caddy[27369]: #011/tmp/gopath_01-16-2336.857153519/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup_server.go:119 +0x21a
Feb 10 12:02:16 webhost caddy[27369]: github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go.(*session).run.func1(0xc0002ac000)
Feb 10 12:02:16 webhost caddy[27369]: #011/tmp/gopath_01-16-2336.857153519/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/session.go:452 +0x3a
Feb 10 12:02:16 webhost caddy[27369]: created by github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go.(*session).run
Feb 10 12:02:16 webhost caddy[27369]: #011/tmp/gopath_01-16-2336.857153519/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/session.go:451 +0x8a
Feb 10 12:02:16 webhost systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 10 12:02:16 webhost systemd[1]: caddy.service: Unit entered failed state.
Feb 10 12:02:16 webhost systemd[1]: caddy.service: Failed with result 'exit-code'.
```

**Comment by marten-seemann** [comment] 2019-02-13 12:11
I thought that was fixed in #1657. To be honest, I don't see how `maybeGetConfigForClient` could possible return a `nil` value. Can you help me debug this?

**Comment by stephanreiter** [comment] 2019-02-13 15:26
This is something that happened in the middle of the night the last few weeks after I had updated caddy. I didn't happen every night, but I repeatedly found the website down in the morning. I am assuming it's caused by some net crawler that indexes the site.
Is this codepath entered when the first packet arrives? If so, I could create a packet trace and we could replay this. The site doesn't receive much traffic, so this might be feasible.

**Comment by marten-seemann** [comment] 2019-02-14 14:58
Yes, this code path is executed during the handshake.
For debugging, please [turn on logging](https://github.com/lucas-clemente/quic-go/wiki/Logging). A few `Printf` statements around the function where the crash happens would probably be useful as well (especially to see the SNI and what `tls.Config` we're handling there).

**Comment by stephanreiter** [comment] 2019-02-15 08:53
Ok! I might have time on Tuesday! Will let you know ...

**Comment by marten-seemann** [comment] 2019-02-22 09:03
@stephanreiter, do you have any updates for us? Would be good to fix this crash as soon as possible.

**Comment by stephanreiter** [comment] 2019-02-22 09:05
No, sorry. I didn't find time; too busy at work.

**Comment by stephanreiter** [comment] 2019-02-22 20:16
I started Caddy with debug-level logging and a tcpdump instance that captures udp packets on port 443. No Printf statements yet because I am just using the latest official caddy binary and didn't want to invest time in building it myself today. Let's see what happens tonight ...

**Comment by marten-seemann** [comment] 2019-02-23 01:12
Thank you for your efforts, Stephan. Looking forward to your results.

**Comment by stephanreiter** [comment] 2019-02-23 12:07
The server hasn't crashed yet. Maybe tonight's the night. :-)

**Comment by stephanreiter** [comment] 2019-02-23 16:18
Alright, it went down again! I'll try to extract the relevant packet(s) from the tracefile and will attempt a replay.

```
2019/02/23 13:00:37 server Serving new connection: 0x7e963db5b52b5474, version gQUIC 39 from [2001:4ca0:108:42:0:443:17:9]:43548
2019/02/23 13:00:37 server Creating new session. Destination Connection ID: 0x7e963db5b52b5474, Source Connection ID: 0x7e963db5b52b5474
2019/02/23 13:00:37 server <- Reading packet 0x1 (1350 bytes) for connection 0x7e963db5b52b5474, unencrypted
2019/02/23 13:00:37 server 	Public Header{ConnectionID: 0x7e963db5b52b5474, PacketNumber: 0x1, PacketNumberLen: 1, Version: gQUIC 39, DiversificationNonce: []byte(nil)}
2019/02/23 13:00:37 server 	Queueing ACK because the first packet should be acknowledged.
2019/02/23 13:00:37 server 	<- &wire.StreamFrame{StreamID: 1, FinBit: false, Offset: 0x0, Data length: 0x514, Offset + Data length: 0x514}
2019/02/23 13:00:37 server Got CHLO:
	SNI : "www.google.de"
	VER : "Q039"
	CCS : "\x01\xe8\x81`\x92\x92\x1a\xe8~퀆\xa2\x15\x82\x91"
	MSPC: "d\x00\x00\x00"
	UAID: "Chrome/63.0.3239.84 Linux x86_64"
	TCID: "\x00\x00\x00\x00"
	PDMD: "X509"
	SMHL: "\x01\x00\x00\x00"
	ICSL: "\x1e\x00\x00\x00"
	CTIM: "le*Z\x00\x00\x00\x00"
	NONP: "\xc1\xa8\xf5\xc46\xd5\xc3?V\xd9\x1f\xac\xbf\xa3>,7jC\x86\xa6FƸ\xf1S\xa5\x81\xf2\xfbh\xd0"
	MIDS: "d\x00\x00\x00"
	SCLS: "\x01\x00\x00\x00"
	CSCT: ""
	COPT: ""
	CFCW: "\x00\x00\xf0\x00"
	SFCW: "\x00\x00`\x00"
	PAD : (1007 bytes)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8e21cc]

goroutine 1638 [running]:
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto.(*certChain).getCertForSNI(0xc00000c7b8, 0xc0002f2270, 0xd, 0xc0002beea0, 0xe9409375, 0x759c519bd0af392e)
	/tmp/gopath_01-16-2336.857153519/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go:66 +0x6c
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto.(*certChain).GetLeafCert(0xc00000c7b8, 0xc0002f2270, 0xd, 0xc00022c638, 0xc0002f2201, 0xd, 0xc0002bef90, 0x10)
	/tmp/gopath_01-16-2336.857153519/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go:51 +0x43
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetupServer).handleMessage(0xc0000e2000, 0xc00039bc00, 0x514, 0x60f, 0xc000170360, 0x1, 0x6e23c1, 0xc0001708d8)
	/tmp/gopath_01-16-2336.857153519/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup_server.go:162 +0x18f
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetupServer).HandleCryptoStream(0xc0000e2000, 0xf, 0xc0002f2888)
	/tmp/gopath_01-16-2336.857153519/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup_server.go:119 +0x21a
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go.(*session).run.func1(0xc0006d4000)
	/tmp/gopath_01-16-2336.857153519/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/session.go:452 +0x3a
created by github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go.(*session).run
	/tmp/gopath_01-16-2336.857153519/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/session.go:451 +0x8a
```

**Comment by stephanreiter** [comment] 2019-02-23 16:27
Here's the packet as an escaped string right from Wireshark:

```
"\xaa\xac\x4f\x33\x29\x02\x40\xa6\x77\x34\x67\xf0\x86\xdd\x60\x00" \
"\x00\x00\x05\x4e\x11\xf9\x20\x01\x4c\xa0\x01\x08\x00\x42\x00\x00" \
"\x04\x43\x00\x17\x00\x09\x2a\x03\xb0\xc0\x00\x03\x00\xd0\x00\x00" \
"\x00\x00\x04\x3e\xa0\x01\xaa\x1c\x01\xbb\x05\x4e\x9a\x33\x0d\x7e" \
"\x96\x3d\xb5\xb5\x2b\x54\x74\x51\x30\x33\x39\x01\x0b\x1d\xa2\xbb" \
"\x2e\x36\x48\x6a\xf7\xdf\x95\x50\xa0\x01\x05\x14\x43\x48\x4c\x4f" \
"\x12\x00\x00\x00\x50\x41\x44\x00\xef\x03\x00\x00\x53\x4e\x49\x00" \
"\xfc\x03\x00\x00\x56\x45\x52\x00\x00\x04\x00\x00\x43\x43\x53\x00" \
"\x10\x04\x00\x00\x4d\x53\x50\x43\x14\x04\x00\x00\x55\x41\x49\x44" \
"\x34\x04\x00\x00\x54\x43\x49\x44\x38\x04\x00\x00\x50\x44\x4d\x44" \
"\x3c\x04\x00\x00\x53\x4d\x48\x4c\x40\x04\x00\x00\x49\x43\x53\x4c" \
"\x44\x04\x00\x00\x43\x54\x49\x4d\x4c\x04\x00\x00\x4e\x4f\x4e\x50" \
"\x6c\x04\x00\x00\x4d\x49\x44\x53\x70\x04\x00\x00\x53\x43\x4c\x53" \
"\x74\x04\x00\x00\x43\x53\x43\x54\x74\x04\x00\x00\x43\x4f\x50\x54" \
"\x74\x04\x00\x00\x43\x46\x43\x57\x78\x04\x00\x00\x53\x46\x43\x57" \
"\x7c\x04\x00\x00\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d" \
"\x2d\x2d\x2d\x77\x77\x77\x2e\x67\x6f\x6f\x67\x6c\x65\x2e\x64\x65" \
"\x51\x30\x33\x39\x01\xe8\x81\x60\x92\x92\x1a\xe8\x7e\xed\x80\x86" \
"\xa2\x15\x82\x91\x64\x00\x00\x00\x43\x68\x72\x6f\x6d\x65\x2f\x36" \
"\x33\x2e\x30\x2e\x33\x32\x33\x39\x2e\x38\x34\x20\x4c\x69\x6e\x75" \
"\x78\x20\x78\x38\x36\x5f\x36\x34\x00\x00\x00\x00\x58\x35\x30\x39" \
"\x01\x00\x00\x00\x1e\x00\x00\x00\x6c\x65\x2a\x5a\x00\x00\x00\x00" \
"\xc1\xa8\xf5\xc4\x36\xd5\xc3\x3f\x56\xd9\x1f\xac\xbf\xa3\x3e\x2c" \
"\x37\x6a\x43\x86\xa6\x46\xc6\xb8\xf1\x53\xa5\x81\xf2\xfb\x68\xd0" \
"\x64\x00\x00\x00\x01\x00\x00\x00\x00\x00\xf0\x00\x00\x00\x60\x00" \
"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" \
"\x00\x00\x00\x00"
```

**Comment by stephanreiter** [comment] 2019-02-23 16:51
@marten-seemann the following mini Python script does a replay of that packet and makes my caddy v.0.10.1 instance crash. An older version is not susceptible, which is what I am running now.

Monday evening I could compile my own caddy with quic-go with debug info and give you more details or even try to fix the bug. If the info I posted here today is already sufficient for you, please go ahead. :-)

```
import binascii

x = binascii.unhexlify("0d7e963db5b52b547451303339010b1da2bb2e36486af7df9550a001051443484c4f1200000050414400ef030000534e4900fc030000564552000004000043435300100400004d535043140400005541494434040000544349443804000050444d443c040000534d484c400400004943534c440400004354494d4c0400004e4f4e506c0400004d4944537004000053434c53740400004353435474040000434f5054740400004346435778040000534643577c0400002d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d7777772e676f6f676c652e64655130333901e8816092921ae87eed8086a2158291640000004368726f6d652f36332e302e333233392e3834204c696e7578207838365f36340000000058353039010000001e0000006c652a5a00000000c1a8f5c436d5c33f56d91facbfa33e2c376a4386a646c6b8f153a581f2fb68d064000000010000000000f000000060000000000000000000000000000000000000000000")

import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.sendto(x, ('123.123.123.123', 443))
```

**Comment by marten-seemann** [comment] 2019-02-24 01:41
Hi @stephanreiter, thank you a lot for your debugging efforts.
I tried to reproduce the problem. I set up a Caddy 0.11.4, and sent it your packet. This is log output I'm getting:
```
caddy_1   | 2019/02/24 01:39:13 server Got CHLO:
caddy_1   | 	SNI : "www.google.de"
caddy_1   | 	VER : "Q039"
caddy_1   | 	CCS : "\x01\xe8\x81`\x92\x92\x1a\xe8~퀆\xa2\x15\x82\x91"
caddy_1   | 	MSPC: "d\x00\x00\x00"
caddy_1   | 	UAID: "Chrome/63.0.3239.84 Linux x86_64"
caddy_1   | 	TCID: "\x00\x00\x00\x00"
caddy_1   | 	PDMD: "X509"
caddy_1   | 	SMHL: "\x01\x00\x00\x00"
caddy_1   | 	ICSL: "\x1e\x00\x00\x00"
caddy_1   | 	CTIM: "le*Z\x00\x00\x00\x00"
caddy_1   | 	NONP: "\xc1\xa8\xf5\xc46\xd5\xc3?V\xd9\x1f\xac\xbf\xa3>,7jC\x86\xa6FƸ\xf1S\xa5\x81\xf2\xfbh\xd0"
caddy_1   | 	MIDS: "d\x00\x00\x00"
caddy_1   | 	SCLS: "\x01\x00\x00\x00"
caddy_1   | 	CSCT: ""
caddy_1   | 	COPT: ""
caddy_1   | 	CFCW: "\x00\x00\xf0\x00"
caddy_1   | 	SFCW: "\x00\x00`\x00"
caddy_1   | 	PAD : (1007 bytes)
caddy_1   | 2019/02/24 01:39:13 server Closing session with error: no certificate available for 'www.google.de'
caddy_1   | 2019/02/24 01:39:13 server -> Sending packet 0x1 (74 bytes) for connection 0x7e963db5b52b5474, unencrypted
caddy_1   | 2019/02/24 01:39:13 server 	Public Header{ConnectionID: 0x7e963db5b52b5474, PacketNumber: 0x1, PacketNumberLen: 2, Version: gQUIC 39, DiversificationNonce: []byte(nil)}
caddy_1   | 2019/02/24 01:39:13 server 	-> &wire.ConnectionCloseFrame{ErrorCode:0x1, ReasonPhrase:"no certificate available for 'www.google.de'"}
caddy_1   | 2019/02/24 01:39:13 server Connection 0x7e963db5b52b5474 closed.
```
which is the correct behavior, since my Caddy doesn't have a certificate for www.google.de.

Can you please double-check the version you're running. Really, in the line that the stack trace is mentioning, there's nothing that could go wrong: https://github.com/mholt/caddy/blob/master/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go#L66

**Comment by stephanreiter** [comment] 2019-02-24 22:06
The crashing caddy is Caddy 0.11.2.
The stable one is Caddy 0.10.10.
I'll try 0.11.4.

**Comment by stephanreiter** [comment] 2019-02-24 22:11
0.11.4 is fine - no surprise, since it worked for you, too! :)

**Closed** 2019-02-27 04:56 UTC
